var searchData=
[
  ['abridgedtypesandsettings_22',['AbridgedTypesAndSettings',['../structAbridgedTypesAndSettings.html',1,'']]],
  ['absoluteconsistency_23',['AbsoluteConsistency',['../enumorg_1_1rocksdb_1_1WALRecoveryMode.html#a7a64f5af4c71aa35cc7b38b55332c12d',1,'org::rocksdb::WALRecoveryMode']]],
  ['abstractcompactionfilter_24',['AbstractCompactionFilter',['../classorg_1_1rocksdb_1_1AbstractCompactionFilter.html',1,'org::rocksdb']]],
  ['abstractcompactionfilter_3c_20slice_20_3e_25',['AbstractCompactionFilter&lt; Slice &gt;',['../classorg_1_1rocksdb_1_1AbstractCompactionFilter.html',1,'org::rocksdb']]],
  ['abstractcompactionfilter_3c_3f_20extends_20org_3a_3arocksdb_3a_3aabstractslice_3c_3f_3e_20_3e_26',['AbstractCompactionFilter&lt;? extends org::rocksdb::AbstractSlice&lt;?&gt; &gt;',['../classorg_1_1rocksdb_1_1AbstractCompactionFilter.html',1,'org::rocksdb']]],
  ['abstractcompactionfilterfactory_27',['AbstractCompactionFilterFactory',['../classorg_1_1rocksdb_1_1AbstractCompactionFilterFactory.html',1,'org::rocksdb']]],
  ['abstractcompactionfilterfactory_3c_20removeemptyvaluecompactionfilter_20_3e_28',['AbstractCompactionFilterFactory&lt; RemoveEmptyValueCompactionFilter &gt;',['../classorg_1_1rocksdb_1_1AbstractCompactionFilterFactory.html',1,'org::rocksdb']]],
  ['abstractcompactionfilterfactory_3c_3f_20extends_20org_3a_3arocksdb_3a_3aabstractcompactionfilter_3c_3f_3e_20_3e_29',['AbstractCompactionFilterFactory&lt;? extends org::rocksdb::AbstractCompactionFilter&lt;?&gt; &gt;',['../classorg_1_1rocksdb_1_1AbstractCompactionFilterFactory.html',1,'org::rocksdb']]],
  ['abstractcompactionfilterfactoryjni_30',['AbstractCompactionFilterFactoryJni',['../classROCKSDB__NAMESPACE_1_1AbstractCompactionFilterFactoryJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstractcomparator_31',['AbstractComparator',['../classorg_1_1rocksdb_1_1AbstractComparator.html',1,'org::rocksdb']]],
  ['abstractcomparatorjni_32',['AbstractComparatorJni',['../classROCKSDB__NAMESPACE_1_1AbstractComparatorJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstractcomparatorjnibridge_33',['AbstractComparatorJniBridge',['../classROCKSDB__NAMESPACE_1_1AbstractComparatorJniBridge.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstracteventlistener_34',['AbstractEventListener',['../classorg_1_1rocksdb_1_1AbstractEventListener.html',1,'org.rocksdb.AbstractEventListener'],['../classorg_1_1rocksdb_1_1AbstractEventListener.html#a7def39853c0897505ec4fcbd19bab724',1,'org.rocksdb.AbstractEventListener.AbstractEventListener()'],['../classorg_1_1rocksdb_1_1AbstractEventListener.html#ac1a726f0478fdd0da55e5dd5f93e597b',1,'org.rocksdb.AbstractEventListener.AbstractEventListener(final EnabledEventCallback... enabledEventCallbacks)']]],
  ['abstracteventlistenerjni_35',['AbstractEventListenerJni',['../classROCKSDB__NAMESPACE_1_1AbstractEventListenerJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstractimmutablenativereference_36',['AbstractImmutableNativeReference',['../classorg_1_1rocksdb_1_1AbstractImmutableNativeReference.html',1,'org::rocksdb']]],
  ['abstractmutableoptions_37',['AbstractMutableOptions',['../classorg_1_1rocksdb_1_1AbstractMutableOptions.html',1,'org.rocksdb.AbstractMutableOptions'],['../classorg_1_1rocksdb_1_1AbstractMutableOptions.html#af2e1769361ff78e91b76d5fddde6f4d2',1,'org.rocksdb.AbstractMutableOptions.AbstractMutableOptions()']]],
  ['abstractmutableoptionsbuilder_38',['AbstractMutableOptionsBuilder',['../classorg_1_1rocksdb_1_1AbstractMutableOptions_1_1AbstractMutableOptionsBuilder.html',1,'org::rocksdb::AbstractMutableOptions']]],
  ['abstractnativereference_39',['AbstractNativeReference',['../classorg_1_1rocksdb_1_1AbstractNativeReference.html',1,'org::rocksdb']]],
  ['abstractrocksiterator_40',['AbstractRocksIterator',['../classorg_1_1rocksdb_1_1AbstractRocksIterator.html',1,'org::rocksdb']]],
  ['abstractrocksiterator_3c_20rocksdb_20_3e_41',['AbstractRocksIterator&lt; RocksDB &gt;',['../classorg_1_1rocksdb_1_1AbstractRocksIterator.html',1,'org::rocksdb']]],
  ['abstractrocksiterator_3c_20sstfilereader_20_3e_42',['AbstractRocksIterator&lt; SstFileReader &gt;',['../classorg_1_1rocksdb_1_1AbstractRocksIterator.html',1,'org::rocksdb']]],
  ['abstractrocksiterator_3c_20writebatchwithindex_20_3e_43',['AbstractRocksIterator&lt; WriteBatchWithIndex &gt;',['../classorg_1_1rocksdb_1_1AbstractRocksIterator.html',1,'org::rocksdb']]],
  ['abstractslice_44',['AbstractSlice',['../classorg_1_1rocksdb_1_1AbstractSlice.html',1,'org::rocksdb']]],
  ['abstractslice_3c_20byte_5b_5d_3e_45',['AbstractSlice&lt; byte[]&gt;',['../classorg_1_1rocksdb_1_1AbstractSlice.html',1,'org::rocksdb']]],
  ['abstractslice_3c_20bytebuffer_20_3e_46',['AbstractSlice&lt; ByteBuffer &gt;',['../classorg_1_1rocksdb_1_1AbstractSlice.html',1,'org::rocksdb']]],
  ['abstractslice_3c_3f_3e_47',['AbstractSlice&lt;?&gt;',['../classorg_1_1rocksdb_1_1AbstractSlice.html',1,'org::rocksdb']]],
  ['abstractslicejni_48',['AbstractSliceJni',['../classROCKSDB__NAMESPACE_1_1AbstractSliceJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstracttablefilter_49',['AbstractTableFilter',['../classorg_1_1rocksdb_1_1AbstractTableFilter.html',1,'org::rocksdb']]],
  ['abstracttablefilterjni_50',['AbstractTableFilterJni',['../classROCKSDB__NAMESPACE_1_1AbstractTableFilterJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstracttracewriter_51',['AbstractTraceWriter',['../classorg_1_1rocksdb_1_1AbstractTraceWriter.html',1,'org::rocksdb']]],
  ['abstracttracewriterjni_52',['AbstractTraceWriterJni',['../classROCKSDB__NAMESPACE_1_1AbstractTraceWriterJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstracttransactionnotifier_53',['AbstractTransactionNotifier',['../classorg_1_1rocksdb_1_1AbstractTransactionNotifier.html',1,'org::rocksdb']]],
  ['abstracttransactionnotifierjni_54',['AbstractTransactionNotifierJni',['../classROCKSDB__NAMESPACE_1_1AbstractTransactionNotifierJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstracttransactiontest_55',['AbstractTransactionTest',['../classorg_1_1rocksdb_1_1AbstractTransactionTest.html',1,'org::rocksdb']]],
  ['abstractwalfilter_56',['AbstractWalFilter',['../classorg_1_1rocksdb_1_1AbstractWalFilter.html',1,'org::rocksdb']]],
  ['abstractwalfilterjni_57',['AbstractWalFilterJni',['../classROCKSDB__NAMESPACE_1_1AbstractWalFilterJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['abstractwritebatch_58',['AbstractWriteBatch',['../classorg_1_1rocksdb_1_1AbstractWriteBatch.html',1,'org::rocksdb']]],
  ['access_59',['access',['../classblock__cache__analyzer_1_1block__cache__pysim_1_1Cache.html#a0514445513d4b11d80bbe4a39ec58972',1,'block_cache_analyzer::block_cache_pysim::Cache']]],
  ['access_5fcount_5f_60',['access_count_',['../classMetadata.html#ab409b10af33c1a0420e77c896c374f92',1,'Metadata']]],
  ['accesshint_61',['AccessHint',['../enumorg_1_1rocksdb_1_1AccessHint.html',1,'org::rocksdb']]],
  ['accesshintjni_62',['AccessHintJni',['../classROCKSDB__NAMESPACE_1_1AccessHintJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['accesshintoncompactionstart_63',['accessHintOnCompactionStart',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#a9fdf68df509cd42cf37c3d493a4ed477',1,'org::rocksdb::DBOptionsInterface']]],
  ['ack_64',['ACK',['../classffd_1_1SocketBase.html#ab3e132b952c3ba14022d68436930c1ea',1,'ffd::SocketBase']]],
  ['action_65',['Action',['../classadvisor_1_1rule__parser_1_1Suggestion_1_1Action.html',1,'advisor.rule_parser.Suggestion.Action'],['../structROCKSDB__NAMESPACE_1_1LoggingForwardVectorIterator_1_1Action.html',1,'ROCKSDB_NAMESPACE::LoggingForwardVectorIterator::Action'],['../enumorg_1_1rocksdb_1_1util_1_1CapturingWriteBatchHandler_1_1Action.html',1,'org.rocksdb.util.CapturingWriteBatchHandler.Action']]],
  ['adaptationcontext_66',['AdaptationContext',['../structROCKSDB__NAMESPACE_1_1WriteThread_1_1AdaptationContext.html',1,'ROCKSDB_NAMESPACE::WriteThread']]],
  ['adaptive_5fmutex_67',['ADAPTIVE_MUTEX',['../enumorg_1_1rocksdb_1_1ReusedSynchronisationType.html#abcb54f94acd297d15db40faaf450bdcd',1,'org.rocksdb.ReusedSynchronisationType.ADAPTIVE_MUTEX()'],['../namespaceROCKSDB__NAMESPACE.html#a347d6c807e04d2e760c74516a6b383e1a4ced06a1f1b9d93aa39b2324f0a3a4d2',1,'ROCKSDB_NAMESPACE::ADAPTIVE_MUTEX()']]],
  ['adaptivetablefactory_68',['AdaptiveTableFactory',['../classROCKSDB__NAMESPACE_1_1AdaptiveTableFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['add_69',['add',['../classorg_1_1rocksdb_1_1CompactionJobStats.html#a9af5d2e806d0f2828d1ce8f1543a95c0',1,'org.rocksdb.CompactionJobStats.add()'],['../classorg_1_1rocksdb_1_1SstFileWriter.html#acb1fee365fa71549ec882eebb1735cb0',1,'org.rocksdb.SstFileWriter.add(final Slice key, final Slice value)'],['../classorg_1_1rocksdb_1_1SstFileWriter.html#a66f1f15f5355f7e22124e509d07dd2e2',1,'org.rocksdb.SstFileWriter.add(final DirectSlice key, final DirectSlice value)']]],
  ['add_5ffile_5fsize_70',['add_file_size',['../classTier.html#ac30281cc22e298423c2ab43e2423ba20',1,'Tier']]],
  ['add_5ffile_5fsize_5fsim_71',['add_file_size_sim',['../classTier.html#a1c0dfacbed35ac2c7d4ee505d23bb795',1,'Tier']]],
  ['addinputselector_72',['AddInputSelector',['../structROCKSDB__NAMESPACE_1_1ribbon_1_1AddInputSelector.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['addinputselector_3c_20key_2c_20resultrow_2c_20true_20_3e_73',['AddInputSelector&lt; Key, ResultRow, true &gt;',['../structROCKSDB__NAMESPACE_1_1ribbon_1_1AddInputSelector_3_01Key_00_01ResultRow_00_01true_01_4.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['addpreparedcallback_74',['AddPreparedCallback',['../classROCKSDB__NAMESPACE_1_1AddPreparedCallback.html',1,'ROCKSDB_NAMESPACE']]],
  ['addref_75',['AddRef',['../structstd_1_1tr1_1_1gtest__internal_1_1AddRef.html',1,'std::tr1::gtest_internal']]],
  ['addref_3c_20t_20_26_20_3e_76',['AddRef&lt; T &amp; &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1AddRef_3_01T_01_6_01_4.html',1,'std::tr1::gtest_internal']]],
  ['addreference_77',['AddReference',['../structtesting_1_1internal_1_1AddReference.html',1,'testing::internal']]],
  ['addreference_3c_20t_20_26_20_3e_78',['AddReference&lt; T &amp; &gt;',['../structtesting_1_1internal_1_1AddReference_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['adhoc_79',['AdHoc',['../classAdHoc.html',1,'AdHoc'],['../classAdHoc.html#aef6752b2c9e04068e390e8f76b2b72fc',1,'AdHoc::AdHoc(int cmd, const std::vector&lt; std::string &gt; &amp;args)'],['../classAdHoc.html#af6dce240d052f74cf3c439d357374984',1,'AdHoc::AdHoc(const std::vector&lt; std::string &gt; &amp;work_req)']]],
  ['adhoc_5fserver_5f_80',['adhoc_server_',['../classFusePriv.html#af2f1ddf138ee836544ec8d40b0500e7c',1,'FusePriv']]],
  ['adhoc_5fwork_5f_81',['adhoc_work_',['../classTierEngineBase.html#a9da651163409acb67dfed08856a258ee',1,'TierEngineBase']]],
  ['advancedcolumnfamilyoptions_82',['AdvancedColumnFamilyOptions',['../structROCKSDB__NAMESPACE_1_1AdvancedColumnFamilyOptions.html',1,'ROCKSDB_NAMESPACE']]],
  ['advancedcolumnfamilyoptionsinterface_83',['AdvancedColumnFamilyOptionsInterface',['../interfaceorg_1_1rocksdb_1_1AdvancedColumnFamilyOptionsInterface.html',1,'org::rocksdb']]],
  ['advancedcolumnfamilyoptionsinterface_3c_20t_20_3e_84',['AdvancedColumnFamilyOptionsInterface&lt; T &gt;',['../interfaceorg_1_1rocksdb_1_1AdvancedColumnFamilyOptionsInterface.html',1,'org::rocksdb']]],
  ['advancedmutablecolumnfamilyoptionsinterface_85',['AdvancedMutableColumnFamilyOptionsInterface',['../interfaceorg_1_1rocksdb_1_1AdvancedMutableColumnFamilyOptionsInterface.html',1,'org::rocksdb']]],
  ['advancedmutablecolumnfamilyoptionsinterface_3c_20t_20_3e_86',['AdvancedMutableColumnFamilyOptionsInterface&lt; T &gt;',['../interfaceorg_1_1rocksdb_1_1AdvancedMutableColumnFamilyOptionsInterface.html',1,'org::rocksdb']]],
  ['adviserandomonopen_87',['adviseRandomOnOpen',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#ad78b0e1aecf95da5d3b8ffeabbf9e952',1,'org::rocksdb::DBOptionsInterface']]],
  ['aggregationoperator_88',['AggregationOperator',['../classadvisor_1_1db__timeseries__parser_1_1TimeSeriesData_1_1AggregationOperator.html',1,'advisor::db_timeseries_parser::TimeSeriesData']]],
  ['alignedbuffer_89',['AlignedBuffer',['../classROCKSDB__NAMESPACE_1_1AlignedBuffer.html',1,'ROCKSDB_NAMESPACE']]],
  ['all_90',['ALL',['../enumorg_1_1rocksdb_1_1StatsLevel.html#abc948fdc7aa21dbfb7f712aaa47d14cf',1,'org::rocksdb::StatsLevel']]],
  ['allkeys_91',['allKeys',['../classorg_1_1rocksdb_1_1AbstractMutableOptions_1_1AbstractMutableOptionsBuilder.html#a75af1e4cf9f4be5a237fdfa4738152d9',1,'org::rocksdb::AbstractMutableOptions::AbstractMutableOptionsBuilder']]],
  ['allocate_92',['Allocate',['../classROCKSDB__NAMESPACE_1_1LibradosWritableFile.html#a253b550bffed642725ad8477032627ab',1,'ROCKSDB_NAMESPACE::LibradosWritableFile']]],
  ['allocator_93',['Allocator',['../classROCKSDB__NAMESPACE_1_1Allocator.html',1,'ROCKSDB_NAMESPACE']]],
  ['alloctracker_94',['AllocTracker',['../classROCKSDB__NAMESPACE_1_1AllocTracker.html',1,'ROCKSDB_NAMESPACE']]],
  ['allow2pc_95',['allow2pc',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#a034cce6ef184078cd47d2da01fef7139',1,'org::rocksdb::DBOptionsInterface']]],
  ['allowblockingflush_96',['allowBlockingFlush',['../classorg_1_1rocksdb_1_1IngestExternalFileOptions.html#a4a9ffb520365e9d40900f0477da2c95d',1,'org::rocksdb::IngestExternalFileOptions']]],
  ['allowcompaction_97',['allowCompaction',['../classorg_1_1rocksdb_1_1CompactionOptionsFIFO.html#a33ed726b2adde946f6f836fde0097dcc',1,'org::rocksdb::CompactionOptionsFIFO']]],
  ['allowconcurrentmemtablewrite_98',['allowConcurrentMemtableWrite',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#a331d1671929cad19559152708681a244',1,'org::rocksdb::DBOptionsInterface']]],
  ['allowfallocate_99',['allowFAllocate',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#a9f391b3ccf518bcf11082b7039ca20a3',1,'org.rocksdb.DBOptionsInterface.allowFAllocate()'],['../classorg_1_1rocksdb_1_1EnvOptions.html#aaf0411189b10d03bc728f9c31f1fcd0c',1,'org.rocksdb.EnvOptions.allowFallocate()']]],
  ['allowglobalseqno_100',['allowGlobalSeqNo',['../classorg_1_1rocksdb_1_1IngestExternalFileOptions.html#a054c723ad6cd659456d2e256c320510b',1,'org::rocksdb::IngestExternalFileOptions']]],
  ['allowingestbehind_101',['allowIngestBehind',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#a908551118f2f7f1edc616fc07d137361',1,'org::rocksdb::DBOptionsInterface']]],
  ['allowmmapreads_102',['allowMmapReads',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#a1ce6b48757c5151a092e41f3d7c2131e',1,'org::rocksdb::DBOptionsInterface']]],
  ['allowmmapwrites_103',['allowMmapWrites',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#ac62b67f344ca4bdc6d7f94ee8477e3cf',1,'org::rocksdb::DBOptionsInterface']]],
  ['allowtrivialmove_104',['allowTrivialMove',['../classorg_1_1rocksdb_1_1CompactionOptionsUniversal.html#a5425199a39fbf38c1d3693533cd128fb',1,'org::rocksdb::CompactionOptionsUniversal']]],
  ['allowwritestall_105',['allowWriteStall',['../classorg_1_1rocksdb_1_1CompactRangeOptions.html#a85abd4945a12c55c900638ca13187a0d',1,'org.rocksdb.CompactRangeOptions.allowWriteStall()'],['../classorg_1_1rocksdb_1_1FlushOptions.html#abc6548665570c91764d198d8ae758325',1,'org.rocksdb.FlushOptions.allowWriteStall()']]],
  ['alltablesfilter_106',['AllTablesFilter',['../classorg_1_1rocksdb_1_1ReadOptionsTest_1_1AllTablesFilter.html',1,'org::rocksdb::ReadOptionsTest']]],
  ['analyzeroptions_107',['AnalyzerOptions',['../classROCKSDB__NAMESPACE_1_1AnalyzerOptions.html',1,'ROCKSDB_NAMESPACE']]],
  ['anylockmanagertest_108',['AnyLockManagerTest',['../classROCKSDB__NAMESPACE_1_1AnyLockManagerTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['append_109',['Append',['../classROCKSDB__NAMESPACE_1_1LibradosWritableFile.html#a3b32936047be6785cbf869fd683f44d9',1,'ROCKSDB_NAMESPACE::LibradosWritableFile::Append()'],['../classROCKSDB__NAMESPACE_1_1StringBuilderJni.html#ae8efdee9875b6005f88f3c8bffb9dae8',1,'ROCKSDB_NAMESPACE::StringBuilderJni::append()']]],
  ['applytoallentriesoptions_110',['ApplyToAllEntriesOptions',['../structROCKSDB__NAMESPACE_1_1Cache_1_1ApplyToAllEntriesOptions.html',1,'ROCKSDB_NAMESPACE::Cache']]],
  ['appmetadata_111',['appMetadata',['../classorg_1_1rocksdb_1_1BackupInfo.html#a5197b17d92a0d521c9b022addba87b7d',1,'org::rocksdb::BackupInfo']]],
  ['approxsizecommand_112',['ApproxSizeCommand',['../classROCKSDB__NAMESPACE_1_1ApproxSizeCommand.html',1,'ROCKSDB_NAMESPACE']]],
  ['arccache_113',['ARCCache',['../classblock__cache__analyzer_1_1block__cache__pysim_1_1ARCCache.html',1,'block_cache_analyzer::block_cache_pysim']]],
  ['arena_114',['Arena',['../classROCKSDB__NAMESPACE_1_1Arena.html',1,'ROCKSDB_NAMESPACE']]],
  ['arena_5fchunk_115',['arena_chunk',['../structmemarena_1_1arena__chunk.html',1,'memarena']]],
  ['arenablocksize_116',['arenaBlockSize',['../interfaceorg_1_1rocksdb_1_1AdvancedMutableColumnFamilyOptionsInterface.html#a25c6589858a30e0a8bc466d15984fdcd',1,'org::rocksdb::AdvancedMutableColumnFamilyOptionsInterface']]],
  ['arenatest_117',['ArenaTest',['../classROCKSDB__NAMESPACE_1_1ArenaTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['arenawrappeddbiter_118',['ArenaWrappedDBIter',['../classROCKSDB__NAMESPACE_1_1ArenaWrappedDBIter.html',1,'ROCKSDB_NAMESPACE']]],
  ['args_5f_119',['args_',['../classAdHoc.html#a6dc2f4facba9a198218aacd4101dd0f4',1,'AdHoc']]],
  ['asanerrorparser_120',['AsanErrorParser',['../classerror__filter_1_1AsanErrorParser.html',1,'error_filter']]],
  ['asserthelper_121',['AssertHelper',['../classtesting_1_1internal_1_1AssertHelper.html',1,'testing::internal']]],
  ['asserthelperdata_122',['AssertHelperData',['../structtesting_1_1internal_1_1AssertHelper_1_1AssertHelperData.html',1,'testing::internal::AssertHelper']]],
  ['assertrunfail_123',['assertRunFAIL',['../classldb__test_1_1LDBTestCase.html#a6d6e0b5b758df05cd5e2fd86ffc4cc29',1,'ldb_test::LDBTestCase']]],
  ['assertrunfailfull_124',['assertRunFAILFull',['../classldb__test_1_1LDBTestCase.html#a90962054a30668d43f0621dd778e8b9e',1,'ldb_test::LDBTestCase']]],
  ['assertrunok_125',['assertRunOK',['../classldb__test_1_1LDBTestCase.html#ad218a6488f2b07d70969c0676f81bf62',1,'ldb_test::LDBTestCase']]],
  ['assertrunokfull_126',['assertRunOKFull',['../classldb__test_1_1LDBTestCase.html#aa1bd2c14405eec407f1474ec7fc26cff',1,'ldb_test::LDBTestCase']]],
  ['associativemergeoperator_127',['AssociativeMergeOperator',['../classROCKSDB__NAMESPACE_1_1AssociativeMergeOperator.html',1,'ROCKSDB_NAMESPACE']]],
  ['atime_128',['atime',['../classFile.html#a9a35d921ff4df4bd28b8ff54645bcaad',1,'File']]],
  ['atime_5f_129',['atime_',['../classFile.html#a8655b795af34ff687488cf2c1d2ec481',1,'File']]],
  ['atomiccompactionunitboundary_130',['AtomicCompactionUnitBoundary',['../structROCKSDB__NAMESPACE_1_1AtomicCompactionUnitBoundary.html',1,'ROCKSDB_NAMESPACE']]],
  ['atomiccounter_131',['AtomicCounter',['../classROCKSDB__NAMESPACE_1_1anon_1_1AtomicCounter.html',1,'ROCKSDB_NAMESPACE::anon']]],
  ['atomicflush_132',['atomicFlush',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#a63c3cb1c2c636d8fd069e256db98216b',1,'org::rocksdb::DBOptionsInterface']]],
  ['atomicflushmemtablestooutputfiles_133',['AtomicFlushMemTablesToOutputFiles',['../classROCKSDB__NAMESPACE_1_1DBImpl.html#a7b7b5a69c5194d564925d400b23b6bbc',1,'ROCKSDB_NAMESPACE::DBImpl']]],
  ['atomicgroupreadbuffer_134',['AtomicGroupReadBuffer',['../classROCKSDB__NAMESPACE_1_1AtomicGroupReadBuffer.html',1,'ROCKSDB_NAMESPACE']]],
  ['autorolllogger_135',['AutoRollLogger',['../classROCKSDB__NAMESPACE_1_1AutoRollLogger.html',1,'ROCKSDB_NAMESPACE']]],
  ['autorollloggertest_136',['AutoRollLoggerTest',['../classROCKSDB__NAMESPACE_1_1AutoRollLoggerTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['autothreadoperationstageupdater_137',['AutoThreadOperationStageUpdater',['../classROCKSDB__NAMESPACE_1_1AutoThreadOperationStageUpdater.html',1,'ROCKSDB_NAMESPACE']]],
  ['autotier_5f_138',['autotier_',['../classFusePriv.html#a0e29ddb6a62e883e3abded18b7a7d491',1,'FusePriv']]],
  ['autovector_139',['autovector',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20activeseqset_3a_3aconst_5fiterator_20_3e_140',['autovector&lt; ActiveSeqSet::const_iterator &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20iteratorwrapperbase_3c_20slice_20_3e_2c_20knumiterreserve_20_3e_141',['autovector&lt; IteratorWrapperBase&lt; Slice &gt;, kNumIterReserve &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3acolumnfamilydata_20_2a_20_3e_142',['autovector&lt; ROCKSDB_NAMESPACE::ColumnFamilyData * &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3afileindexer_3a_3aindexlevel_20_3e_143',['autovector&lt; ROCKSDB_NAMESPACE::FileIndexer::IndexLevel &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3aingestedfileinfo_20_3e_144',['autovector&lt; ROCKSDB_NAMESPACE::IngestedFileInfo &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3alevelfilesbrief_20_3e_145',['autovector&lt; ROCKSDB_NAMESPACE::LevelFilesBrief &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3alevelfilesbrief_2c_202_20_3e_146',['autovector&lt; ROCKSDB_NAMESPACE::LevelFilesBrief, 2 &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3alog_3a_3awriter_20_2a_20_3e_147',['autovector&lt; ROCKSDB_NAMESPACE::log::Writer * &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3alogbuffer_3a_3abufferedlog_20_2a_20_3e_148',['autovector&lt; ROCKSDB_NAMESPACE::LogBuffer::BufferedLog * &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3amemtable_20_2a_20_3e_149',['autovector&lt; ROCKSDB_NAMESPACE::MemTable * &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3aprotectioninfokvoc_20_3e_150',['autovector&lt; ROCKSDB_NAMESPACE::ProtectionInfoKVOC &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3asuperversion_20_2a_20_3e_151',['autovector&lt; ROCKSDB_NAMESPACE::SuperVersion * &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3asuperversioncontext_3a_3awritestallnotification_20_3e_152',['autovector&lt; ROCKSDB_NAMESPACE::SuperVersionContext::WriteStallNotification &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3atruncatedrangedeliterator_20_2a_20_3e_153',['autovector&lt; ROCKSDB_NAMESPACE::TruncatedRangeDelIterator * &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20rocksdb_5fnamespace_3a_3aversionedit_20_2a_20_3e_154',['autovector&lt; ROCKSDB_NAMESPACE::VersionEdit * &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20std_3a_3apair_3c_20int_2c_20rocksdb_5fnamespace_3a_3afilemetadata_20_2a_20_3e_20_3e_155',['autovector&lt; std::pair&lt; int, ROCKSDB_NAMESPACE::FileMetaData * &gt; &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20t_20_3e_156',['autovector&lt; T &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20transactionid_20_3e_157',['autovector&lt; TransactionID &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovector_3c_20uint32_5ft_20_3e_158',['autovector&lt; uint32_t &gt;',['../classROCKSDB__NAMESPACE_1_1autovector.html',1,'ROCKSDB_NAMESPACE']]],
  ['autovectortest_159',['AutoVectorTest',['../classROCKSDB__NAMESPACE_1_1AutoVectorTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['avoidflushduringrecovery_160',['avoidFlushDuringRecovery',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#ae908ae031111edf4260af007bf272e04',1,'org::rocksdb::DBOptionsInterface']]],
  ['avoidflushduringshutdown_161',['avoidFlushDuringShutdown',['../interfaceorg_1_1rocksdb_1_1MutableDBOptionsInterface.html#a80143dae20f89694a880b00af79db3e1',1,'org::rocksdb::MutableDBOptionsInterface']]],
  ['avoidunnecessaryblockingio_162',['avoidUnnecessaryBlockingIO',['../interfaceorg_1_1rocksdb_1_1DBOptionsInterface.html#ae79842f53542261408d641d4937238e9',1,'org::rocksdb::DBOptionsInterface']]]
];
