var searchData=
[
  ['random_6366',['Random',['../classtesting_1_1internal_1_1Random.html',1,'testing::internal::Random'],['../classROCKSDB__NAMESPACE_1_1Random.html',1,'ROCKSDB_NAMESPACE::Random']]],
  ['random32_6367',['Random32',['../classROCKSDB__NAMESPACE_1_1Random32.html',1,'ROCKSDB_NAMESPACE']]],
  ['random32bit_6368',['Random32Bit',['../classorg_1_1rocksdb_1_1PlatformRandomHelper_1_1Random32Bit.html',1,'org::rocksdb::PlatformRandomHelper']]],
  ['random64_6369',['Random64',['../classROCKSDB__NAMESPACE_1_1Random64.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomaccesscachefile_6370',['RandomAccessCacheFile',['../classROCKSDB__NAMESPACE_1_1RandomAccessCacheFile.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomaccessfile_6371',['RandomAccessFile',['../classROCKSDB__NAMESPACE_1_1RandomAccessFile.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomaccessfilemirror_6372',['RandomAccessFileMirror',['../classROCKSDB__NAMESPACE_1_1RandomAccessFileMirror.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomaccessfilereader_6373',['RandomAccessFileReader',['../classROCKSDB__NAMESPACE_1_1RandomAccessFileReader.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomaccessfilereadertest_6374',['RandomAccessFileReaderTest',['../classROCKSDB__NAMESPACE_1_1RandomAccessFileReaderTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomaccessfilewrapper_6375',['RandomAccessFileWrapper',['../classROCKSDB__NAMESPACE_1_1RandomAccessFileWrapper.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomgenerator_6376',['RandomGenerator',['../classorg_1_1rocksdb_1_1benchmark_1_1DbBenchmark_1_1RandomGenerator.html',1,'org::rocksdb::benchmark::DbBenchmark']]],
  ['randomrwfile_6377',['RandomRWFile',['../classROCKSDB__NAMESPACE_1_1RandomRWFile.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomrwfilewithmirrorstring_6378',['RandomRWFileWithMirrorString',['../classROCKSDB__NAMESPACE_1_1RandomRWFileWithMirrorString.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomrwfilewrapper_6379',['RandomRWFileWrapper',['../classROCKSDB__NAMESPACE_1_1RandomRWFileWrapper.html',1,'ROCKSDB_NAMESPACE']]],
  ['randomrwstringsink_6380',['RandomRWStringSink',['../classROCKSDB__NAMESPACE_1_1test_1_1RandomRWStringSink.html',1,'ROCKSDB_NAMESPACE::test']]],
  ['randomtransactioninserter_6381',['RandomTransactionInserter',['../classROCKSDB__NAMESPACE_1_1RandomTransactionInserter.html',1,'ROCKSDB_NAMESPACE']]],
  ['range_6382',['Range',['../structROCKSDB__NAMESPACE_1_1Range.html',1,'ROCKSDB_NAMESPACE::Range'],['../classorg_1_1rocksdb_1_1Range.html',1,'org.rocksdb.Range'],['../classROCKSDB__NAMESPACE_1_1MultiGetContext_1_1Range.html',1,'ROCKSDB_NAMESPACE::MultiGetContext::Range']]],
  ['range_5fbuffer_6383',['range_buffer',['../classtoku_1_1range__buffer.html',1,'toku']]],
  ['rangedeadlockinfo_6384',['RangeDeadlockInfo',['../structROCKSDB__NAMESPACE_1_1RangeDeadlockInfo.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangedeadlockpath_6385',['RangeDeadlockPath',['../structROCKSDB__NAMESPACE_1_1RangeDeadlockPath.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangedelaggregator_6386',['RangeDelAggregator',['../classROCKSDB__NAMESPACE_1_1RangeDelAggregator.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangedelaggregatortest_6387',['RangeDelAggregatorTest',['../classROCKSDB__NAMESPACE_1_1RangeDelAggregatorTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangegenerator_6388',['RangeGenerator',['../classtesting_1_1internal_1_1RangeGenerator.html',1,'testing::internal']]],
  ['rangelockinfo_6389',['RangeLockInfo',['../structROCKSDB__NAMESPACE_1_1RangeLockInfo.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangelockingtest_6390',['RangeLockingTest',['../classROCKSDB__NAMESPACE_1_1RangeLockingTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangelocklist_6391',['RangeLockList',['../classROCKSDB__NAMESPACE_1_1RangeLockList.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangelockmanagerbase_6392',['RangeLockManagerBase',['../classROCKSDB__NAMESPACE_1_1RangeLockManagerBase.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangelockmanagerhandle_6393',['RangeLockManagerHandle',['../classROCKSDB__NAMESPACE_1_1RangeLockManagerHandle.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangelockrequest_6394',['RangeLockRequest',['../structROCKSDB__NAMESPACE_1_1RangeLockRequest.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangeptr_6395',['RangePtr',['../structROCKSDB__NAMESPACE_1_1RangePtr.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangetombstone_6396',['RangeTombstone',['../structROCKSDB__NAMESPACE_1_1RangeTombstone.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangetombstonefragmentertest_6397',['RangeTombstoneFragmenterTest',['../classROCKSDB__NAMESPACE_1_1RangeTombstoneFragmenterTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangetombstonestack_6398',['RangeTombstoneStack',['../structROCKSDB__NAMESPACE_1_1FragmentedRangeTombstoneList_1_1RangeTombstoneStack.html',1,'ROCKSDB_NAMESPACE::FragmentedRangeTombstoneList']]],
  ['rangetombstonestackendcomparator_6399',['RangeTombstoneStackEndComparator',['../structROCKSDB__NAMESPACE_1_1FragmentedRangeTombstoneIterator_1_1RangeTombstoneStackEndComparator.html',1,'ROCKSDB_NAMESPACE::FragmentedRangeTombstoneIterator']]],
  ['rangetombstonestackstartcomparator_6400',['RangeTombstoneStackStartComparator',['../structROCKSDB__NAMESPACE_1_1FragmentedRangeTombstoneIterator_1_1RangeTombstoneStackStartComparator.html',1,'ROCKSDB_NAMESPACE::FragmentedRangeTombstoneIterator']]],
  ['rangetreelockmanager_6401',['RangeTreeLockManager',['../classROCKSDB__NAMESPACE_1_1RangeTreeLockManager.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangetreelocktracker_6402',['RangeTreeLockTracker',['../classROCKSDB__NAMESPACE_1_1RangeTreeLockTracker.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangetreelocktrackerfactory_6403',['RangeTreeLockTrackerFactory',['../classROCKSDB__NAMESPACE_1_1RangeTreeLockTrackerFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['rangewithsize_6404',['RangeWithSize',['../structROCKSDB__NAMESPACE_1_1RangeWithSize.html',1,'ROCKSDB_NAMESPACE']]],
  ['ratelimiter_6405',['RateLimiter',['../classorg_1_1rocksdb_1_1RateLimiter.html',1,'org.rocksdb.RateLimiter'],['../classROCKSDB__NAMESPACE_1_1RateLimiter.html',1,'ROCKSDB_NAMESPACE::RateLimiter']]],
  ['ratelimitermode_6406',['RateLimiterMode',['../enumorg_1_1rocksdb_1_1RateLimiterMode.html',1,'org::rocksdb']]],
  ['ratelimitermodejni_6407',['RateLimiterModeJni',['../classROCKSDB__NAMESPACE_1_1RateLimiterModeJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['ratelimitertest_6408',['RateLimiterTest',['../classorg_1_1rocksdb_1_1RateLimiterTest.html',1,'org.rocksdb.RateLimiterTest'],['../classROCKSDB__NAMESPACE_1_1RateLimiterTest.html',1,'ROCKSDB_NAMESPACE::RateLimiterTest']]],
  ['re_6409',['RE',['../classtesting_1_1internal_1_1RE.html',1,'testing::internal']]],
  ['reactiveversionset_6410',['ReactiveVersionSet',['../classROCKSDB__NAMESPACE_1_1ReactiveVersionSet.html',1,'ROCKSDB_NAMESPACE']]],
  ['readablewritebatch_6411',['ReadableWriteBatch',['../classROCKSDB__NAMESPACE_1_1ReadableWriteBatch.html',1,'ROCKSDB_NAMESPACE']]],
  ['readaheadrandomaccessfiletest_6412',['ReadaheadRandomAccessFileTest',['../classROCKSDB__NAMESPACE_1_1ReadaheadRandomAccessFileTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['readaheadsequentialfiletest_6413',['ReadaheadSequentialFileTest',['../classROCKSDB__NAMESPACE_1_1ReadaheadSequentialFileTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['readcallback_6414',['ReadCallback',['../classROCKSDB__NAMESPACE_1_1ReadCallback.html',1,'ROCKSDB_NAMESPACE']]],
  ['reader_6415',['Reader',['../classROCKSDB__NAMESPACE_1_1log_1_1Reader.html',1,'ROCKSDB_NAMESPACE::log']]],
  ['readlock_6416',['ReadLock',['../classROCKSDB__NAMESPACE_1_1ReadLock.html',1,'ROCKSDB_NAMESPACE']]],
  ['readonlyfilesystem_6417',['ReadOnlyFileSystem',['../classROCKSDB__NAMESPACE_1_1ReadOnlyFileSystem.html',1,'ROCKSDB_NAMESPACE']]],
  ['readonlytest_6418',['ReadOnlyTest',['../classorg_1_1rocksdb_1_1ReadOnlyTest.html',1,'org::rocksdb']]],
  ['readoptions_6419',['ReadOptions',['../structROCKSDB__NAMESPACE_1_1TransactionLogIterator_1_1ReadOptions.html',1,'ROCKSDB_NAMESPACE::TransactionLogIterator::ReadOptions'],['../classorg_1_1rocksdb_1_1ReadOptions.html',1,'org.rocksdb.ReadOptions'],['../structROCKSDB__NAMESPACE_1_1ReadOptions.html',1,'ROCKSDB_NAMESPACE::ReadOptions']]],
  ['readoptionsjni_6420',['ReadOptionsJni',['../classROCKSDB__NAMESPACE_1_1ReadOptionsJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['readoptionstest_6421',['ReadOptionsTest',['../classorg_1_1rocksdb_1_1ReadOptionsTest.html',1,'org::rocksdb']]],
  ['readrangedelaggregator_6422',['ReadRangeDelAggregator',['../classROCKSDB__NAMESPACE_1_1ReadRangeDelAggregator.html',1,'ROCKSDB_NAMESPACE']]],
  ['readrequest_6423',['ReadRequest',['../structROCKSDB__NAMESPACE_1_1ReadRequest.html',1,'ROCKSDB_NAMESPACE']]],
  ['readtier_6424',['ReadTier',['../enumorg_1_1rocksdb_1_1ReadTier.html',1,'org::rocksdb']]],
  ['readunlock_6425',['ReadUnlock',['../classROCKSDB__NAMESPACE_1_1ReadUnlock.html',1,'ROCKSDB_NAMESPACE']]],
  ['realcompaction_6426',['RealCompaction',['../classROCKSDB__NAMESPACE_1_1CompactionIterator_1_1RealCompaction.html',1,'ROCKSDB_NAMESPACE::CompactionIterator']]],
  ['record_6427',['record',['../classtoku_1_1range__buffer_1_1iterator_1_1record.html',1,'toku::range_buffer::iterator']]],
  ['record_5fheader_6428',['record_header',['../structtoku_1_1range__buffer_1_1record__header.html',1,'toku::range_buffer']]],
  ['recoveredtransaction_6429',['RecoveredTransaction',['../structROCKSDB__NAMESPACE_1_1DBImpl_1_1RecoveredTransaction.html',1,'ROCKSDB_NAMESPACE::DBImpl']]],
  ['recoverytesthelper_6430',['RecoveryTestHelper',['../classROCKSDB__NAMESPACE_1_1RecoveryTestHelper.html',1,'ROCKSDB_NAMESPACE']]],
  ['reducedblevelscommand_6431',['ReduceDBLevelsCommand',['../classROCKSDB__NAMESPACE_1_1ReduceDBLevelsCommand.html',1,'ROCKSDB_NAMESPACE']]],
  ['reduceleveltest_6432',['ReduceLevelTest',['../classROCKSDB__NAMESPACE_1_1ReduceLevelTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['reftag_6433',['RefTag',['../structfolly_1_1detail_1_1InlineFunctionRef_3_01ReturnType_07Args_8_8_8_08_00_01Size_01_4_1_1RefTag.html',1,'folly::detail::InlineFunctionRef&lt; ReturnType(Args...), Size &gt;']]],
  ['regex_6434',['Regex',['../classROCKSDB__NAMESPACE_1_1Regex.html',1,'ROCKSDB_NAMESPACE']]],
  ['registereddeleter_6435',['RegisteredDeleter',['../structROCKSDB__NAMESPACE_1_1cache__entry__roles__detail_1_1RegisteredDeleter.html',1,'ROCKSDB_NAMESPACE::cache_entry_roles_detail']]],
  ['registerednoopdeleter_6436',['RegisteredNoopDeleter',['../structROCKSDB__NAMESPACE_1_1cache__entry__roles__detail_1_1RegisteredNoopDeleter.html',1,'ROCKSDB_NAMESPACE::cache_entry_roles_detail']]],
  ['registeredoptions_6437',['RegisteredOptions',['../structROCKSDB__NAMESPACE_1_1Configurable_1_1RegisteredOptions.html',1,'ROCKSDB_NAMESPACE::Configurable']]],
  ['regularkeysstartwitha_6438',['RegularKeysStartWithA',['../classROCKSDB__NAMESPACE_1_1RegularKeysStartWithA.html',1,'ROCKSDB_NAMESPACE']]],
  ['regularkeysstartwithabackwardcompatible_6439',['RegularKeysStartWithABackwardCompatible',['../classROCKSDB__NAMESPACE_1_1RegularKeysStartWithABackwardCompatible.html',1,'ROCKSDB_NAMESPACE']]],
  ['regularkeysstartwithafactory_6440',['RegularKeysStartWithAFactory',['../classROCKSDB__NAMESPACE_1_1RegularKeysStartWithAFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['regularkeysstartwithainternal_6441',['RegularKeysStartWithAInternal',['../classROCKSDB__NAMESPACE_1_1RegularKeysStartWithAInternal.html',1,'ROCKSDB_NAMESPACE']]],
  ['relationtosourcecopy_6442',['RelationToSourceCopy',['../structtesting_1_1internal_1_1RelationToSourceCopy.html',1,'testing::internal']]],
  ['relationtosourcereference_6443',['RelationToSourceReference',['../structtesting_1_1internal_1_1RelationToSourceReference.html',1,'testing::internal']]],
  ['remapfilesystem_6444',['RemapFileSystem',['../classROCKSDB__NAMESPACE_1_1RemapFileSystem.html',1,'ROCKSDB_NAMESPACE']]],
  ['remapsharedfilesystem_6445',['RemapSharedFileSystem',['../classROCKSDB__NAMESPACE_1_1BackupEngineImpl_1_1RemapSharedFileSystem.html',1,'ROCKSDB_NAMESPACE::BackupEngineImpl']]],
  ['remove_5fcvref_6446',['remove_cvref',['../structfolly_1_1remove__cvref.html',1,'folly']]],
  ['removeconst_6447',['RemoveConst',['../structtesting_1_1internal_1_1RemoveConst.html',1,'testing::internal']]],
  ['removeconst_3c_20const_20t_20_3e_6448',['RemoveConst&lt; const T &gt;',['../structtesting_1_1internal_1_1RemoveConst_3_01const_01T_01_4.html',1,'testing::internal']]],
  ['removeconst_3c_20const_20t_5bn_5d_3e_6449',['RemoveConst&lt; const T[N]&gt;',['../structtesting_1_1internal_1_1RemoveConst_3_01const_01T_0fN_0e_4.html',1,'testing::internal']]],
  ['removeemptyvaluecompactionfilter_6450',['RemoveEmptyValueCompactionFilter',['../classROCKSDB__NAMESPACE_1_1RemoveEmptyValueCompactionFilter.html',1,'ROCKSDB_NAMESPACE::RemoveEmptyValueCompactionFilter'],['../classorg_1_1rocksdb_1_1RemoveEmptyValueCompactionFilter.html',1,'org.rocksdb.RemoveEmptyValueCompactionFilter']]],
  ['removeemptyvaluecompactionfilterfactory_6451',['RemoveEmptyValueCompactionFilterFactory',['../classorg_1_1rocksdb_1_1test_1_1RemoveEmptyValueCompactionFilterFactory.html',1,'org::rocksdb::test']]],
  ['removereference_6452',['RemoveReference',['../structtesting_1_1internal_1_1RemoveReference.html',1,'testing::internal']]],
  ['removereference_3c_20t_20_26_20_3e_6453',['RemoveReference&lt; T &amp; &gt;',['../structtesting_1_1internal_1_1RemoveReference_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['renamecurrenttest_6454',['RenameCurrentTest',['../classROCKSDB__NAMESPACE_1_1RenameCurrentTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['rep_6455',['Rep',['../structROCKSDB__NAMESPACE_1_1BlockBasedTable_1_1Rep.html',1,'ROCKSDB_NAMESPACE::BlockBasedTable::Rep'],['../classROCKSDB__NAMESPACE_1_1CompressionContextCache_1_1Rep.html',1,'ROCKSDB_NAMESPACE::CompressionContextCache::Rep'],['../structROCKSDB__NAMESPACE_1_1WriteBatchWithIndex_1_1Rep.html',1,'ROCKSDB_NAMESPACE::WriteBatchWithIndex::Rep'],['../classROCKSDB__NAMESPACE_1_1VersionBuilder_1_1Rep.html',1,'ROCKSDB_NAMESPACE::VersionBuilder::Rep'],['../structROCKSDB__NAMESPACE_1_1BlockBasedTableBuilder_1_1Rep.html',1,'ROCKSDB_NAMESPACE::BlockBasedTableBuilder::Rep'],['../structROCKSDB__NAMESPACE_1_1SstFileReader_1_1Rep.html',1,'ROCKSDB_NAMESPACE::SstFileReader::Rep'],['../structROCKSDB__NAMESPACE_1_1SstFileWriter_1_1Rep.html',1,'ROCKSDB_NAMESPACE::SstFileWriter::Rep']]],
  ['repaircommand_6456',['RepairCommand',['../classROCKSDB__NAMESPACE_1_1RepairCommand.html',1,'ROCKSDB_NAMESPACE']]],
  ['repairtest_6457',['RepairTest',['../classROCKSDB__NAMESPACE_1_1RepairTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['repeatablethread_6458',['RepeatableThread',['../classROCKSDB__NAMESPACE_1_1RepeatableThread.html',1,'ROCKSDB_NAMESPACE']]],
  ['repeatablethreadtest_6459',['RepeatableThreadTest',['../classRepeatableThreadTest.html',1,'']]],
  ['replayer_6460',['Replayer',['../classROCKSDB__NAMESPACE_1_1Replayer.html',1,'ROCKSDB_NAMESPACE']]],
  ['replayerimpl_6461',['ReplayerImpl',['../classROCKSDB__NAMESPACE_1_1ReplayerImpl.html',1,'ROCKSDB_NAMESPACE']]],
  ['replayerworkerarg_6462',['ReplayerWorkerArg',['../structROCKSDB__NAMESPACE_1_1ReplayerWorkerArg.html',1,'ROCKSDB_NAMESPACE']]],
  ['replayoptions_6463',['ReplayOptions',['../structROCKSDB__NAMESPACE_1_1ReplayOptions.html',1,'ROCKSDB_NAMESPACE']]],
  ['reportcollector_6464',['ReportCollector',['../classROCKSDB__NAMESPACE_1_1log_1_1LogTest_1_1ReportCollector.html',1,'ROCKSDB_NAMESPACE::log::LogTest::ReportCollector'],['../classROCKSDB__NAMESPACE_1_1log_1_1RetriableLogTest_1_1ReportCollector.html',1,'ROCKSDB_NAMESPACE::log::RetriableLogTest::ReportCollector']]],
  ['reporter_6465',['Reporter',['../classROCKSDB__NAMESPACE_1_1log_1_1Reader_1_1Reporter.html',1,'ROCKSDB_NAMESPACE::log::Reader']]],
  ['req_6466',['Req',['../structROCKSDB__NAMESPACE_1_1GenericRateLimiter_1_1Req.html',1,'ROCKSDB_NAMESPACE::GenericRateLimiter']]],
  ['requestwithoutreturn_6467',['RequestWithoutReturn',['../classfolly_1_1detail_1_1distributed__mutex_1_1RequestWithoutReturn.html',1,'folly::detail::distributed_mutex']]],
  ['requestwithreturn_6468',['RequestWithReturn',['../classfolly_1_1detail_1_1distributed__mutex_1_1RequestWithReturn.html',1,'folly::detail::distributed_mutex']]],
  ['restoreaftercopyorcreateworkitem_6469',['RestoreAfterCopyOrCreateWorkItem',['../structROCKSDB__NAMESPACE_1_1BackupEngineImpl_1_1RestoreAfterCopyOrCreateWorkItem.html',1,'ROCKSDB_NAMESPACE::BackupEngineImpl']]],
  ['restorecommand_6470',['RestoreCommand',['../classROCKSDB__NAMESPACE_1_1RestoreCommand.html',1,'ROCKSDB_NAMESPACE']]],
  ['restoreoptions_6471',['RestoreOptions',['../structROCKSDB__NAMESPACE_1_1RestoreOptions.html',1,'ROCKSDB_NAMESPACE::RestoreOptions'],['../classorg_1_1rocksdb_1_1RestoreOptions.html',1,'org.rocksdb.RestoreOptions']]],
  ['retriablelogtest_6472',['RetriableLogTest',['../classROCKSDB__NAMESPACE_1_1log_1_1RetriableLogTest.html',1,'ROCKSDB_NAMESPACE::log']]],
  ['return_5ftype_5fhelper_6473',['return_type_helper',['../structfolly_1_1array__detail_1_1return__type__helper.html',1,'folly::array_detail']]],
  ['return_5ftype_5fhelper_3c_20void_2c_20tlist_2e_2e_2e_20_3e_6474',['return_type_helper&lt; void, TList... &gt;',['../structfolly_1_1array__detail_1_1return__type__helper_3_01void_00_01TList_8_8_8_01_4.html',1,'folly::array_detail']]],
  ['reusedsynchronisationtype_6475',['ReusedSynchronisationType',['../enumorg_1_1rocksdb_1_1ReusedSynchronisationType.html',1,'org::rocksdb']]],
  ['reusedsynchronisationtypejni_6476',['ReusedSynchronisationTypeJni',['../classROCKSDB__NAMESPACE_1_1ReusedSynchronisationTypeJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['reversebytewisecomparator_6477',['ReverseBytewiseComparator',['../classorg_1_1rocksdb_1_1util_1_1ReverseBytewiseComparator.html',1,'org::rocksdb::util']]],
  ['reversebytewisecomparatorinttest_6478',['ReverseBytewiseComparatorIntTest',['../classorg_1_1rocksdb_1_1util_1_1ReverseBytewiseComparatorIntTest.html',1,'org::rocksdb::util']]],
  ['reverserangedeliterator_6479',['ReverseRangeDelIterator',['../classROCKSDB__NAMESPACE_1_1ReverseRangeDelIterator.html',1,'ROCKSDB_NAMESPACE']]],
  ['ribbontest_6480',['RibbonTest',['../classRibbonTest.html',1,'']]],
  ['ribbontypeparamtest_6481',['RibbonTypeParamTest',['../classRibbonTypeParamTest.html',1,'']]],
  ['rockscallbackobject_6482',['RocksCallbackObject',['../classorg_1_1rocksdb_1_1RocksCallbackObject.html',1,'org::rocksdb']]],
  ['rocksdb_6483',['RocksDB',['../classorg_1_1rocksdb_1_1RocksDB.html',1,'org::rocksdb']]],
  ['rocksdb_5fbackup_5fengine_5finfo_5ft_6484',['rocksdb_backup_engine_info_t',['../structrocksdb__backup__engine__info__t.html',1,'']]],
  ['rocksdb_5fbackup_5fengine_5ft_6485',['rocksdb_backup_engine_t',['../structrocksdb__backup__engine__t.html',1,'']]],
  ['rocksdb_5fbackupable_5fdb_5foptions_5ft_6486',['rocksdb_backupable_db_options_t',['../structrocksdb__backupable__db__options__t.html',1,'']]],
  ['rocksdb_5fblock_5fbased_5ftable_5foptions_5ft_6487',['rocksdb_block_based_table_options_t',['../structrocksdb__block__based__table__options__t.html',1,'']]],
  ['rocksdb_5fcache_5ft_6488',['rocksdb_cache_t',['../structrocksdb__cache__t.html',1,'']]],
  ['rocksdb_5fcheckpoint_5ft_6489',['rocksdb_checkpoint_t',['../structrocksdb__checkpoint__t.html',1,'']]],
  ['rocksdb_5fcolumn_5ffamily_5fhandle_5ft_6490',['rocksdb_column_family_handle_t',['../structrocksdb__column__family__handle__t.html',1,'']]],
  ['rocksdb_5fcompactionfilter_5ft_6491',['rocksdb_compactionfilter_t',['../structrocksdb__compactionfilter__t.html',1,'']]],
  ['rocksdb_5fcompactionfiltercontext_5ft_6492',['rocksdb_compactionfiltercontext_t',['../structrocksdb__compactionfiltercontext__t.html',1,'']]],
  ['rocksdb_5fcompactionfilterfactory_5ft_6493',['rocksdb_compactionfilterfactory_t',['../structrocksdb__compactionfilterfactory__t.html',1,'']]],
  ['rocksdb_5fcompactoptions_5ft_6494',['rocksdb_compactoptions_t',['../structrocksdb__compactoptions__t.html',1,'']]],
  ['rocksdb_5fcomparator_5ft_6495',['rocksdb_comparator_t',['../structrocksdb__comparator__t.html',1,'']]],
  ['rocksdb_5fcuckoo_5ftable_5foptions_5ft_6496',['rocksdb_cuckoo_table_options_t',['../structrocksdb__cuckoo__table__options__t.html',1,'']]],
  ['rocksdb_5fdbpath_5ft_6497',['rocksdb_dbpath_t',['../structrocksdb__dbpath__t.html',1,'']]],
  ['rocksdb_5fenv_5ft_6498',['rocksdb_env_t',['../structrocksdb__env__t.html',1,'']]],
  ['rocksdb_5fenvoptions_5ft_6499',['rocksdb_envoptions_t',['../structrocksdb__envoptions__t.html',1,'']]],
  ['rocksdb_5ffifo_5fcompaction_5foptions_5ft_6500',['rocksdb_fifo_compaction_options_t',['../structrocksdb__fifo__compaction__options__t.html',1,'']]],
  ['rocksdb_5ffilelock_5ft_6501',['rocksdb_filelock_t',['../structrocksdb__filelock__t.html',1,'']]],
  ['rocksdb_5ffilterpolicy_5ft_6502',['rocksdb_filterpolicy_t',['../structrocksdb__filterpolicy__t.html',1,'']]],
  ['rocksdb_5fflushoptions_5ft_6503',['rocksdb_flushoptions_t',['../structrocksdb__flushoptions__t.html',1,'']]],
  ['rocksdb_5fingestexternalfileoptions_5ft_6504',['rocksdb_ingestexternalfileoptions_t',['../structrocksdb__ingestexternalfileoptions__t.html',1,'']]],
  ['rocksdb_5fiterator_5ft_6505',['rocksdb_iterator_t',['../structrocksdb__iterator__t.html',1,'']]],
  ['rocksdb_5flivefiles_5ft_6506',['rocksdb_livefiles_t',['../structrocksdb__livefiles__t.html',1,'']]],
  ['rocksdb_5flogger_5ft_6507',['rocksdb_logger_t',['../structrocksdb__logger__t.html',1,'']]],
  ['rocksdb_5flru_5fcache_5foptions_5ft_6508',['rocksdb_lru_cache_options_t',['../structrocksdb__lru__cache__options__t.html',1,'']]],
  ['rocksdb_5fmemory_5fallocator_5ft_6509',['rocksdb_memory_allocator_t',['../structrocksdb__memory__allocator__t.html',1,'']]],
  ['rocksdb_5fmemory_5fconsumers_5ft_6510',['rocksdb_memory_consumers_t',['../structrocksdb__memory__consumers__t.html',1,'']]],
  ['rocksdb_5fmemory_5fusage_5ft_6511',['rocksdb_memory_usage_t',['../structrocksdb__memory__usage__t.html',1,'']]],
  ['rocksdb_5fmergeoperator_5ft_6512',['rocksdb_mergeoperator_t',['../structrocksdb__mergeoperator__t.html',1,'']]],
  ['rocksdb_5foptimistictransaction_5foptions_5ft_6513',['rocksdb_optimistictransaction_options_t',['../structrocksdb__optimistictransaction__options__t.html',1,'']]],
  ['rocksdb_5foptimistictransactiondb_5ft_6514',['rocksdb_optimistictransactiondb_t',['../structrocksdb__optimistictransactiondb__t.html',1,'']]],
  ['rocksdb_5foptions_5ft_6515',['rocksdb_options_t',['../structrocksdb__options__t.html',1,'']]],
  ['rocksdb_5fperfcontext_5ft_6516',['rocksdb_perfcontext_t',['../structrocksdb__perfcontext__t.html',1,'']]],
  ['rocksdb_5fpinnableslice_5ft_6517',['rocksdb_pinnableslice_t',['../structrocksdb__pinnableslice__t.html',1,'']]],
  ['rocksdb_5frandomfile_5ft_6518',['rocksdb_randomfile_t',['../structrocksdb__randomfile__t.html',1,'']]],
  ['rocksdb_5fratelimiter_5ft_6519',['rocksdb_ratelimiter_t',['../structrocksdb__ratelimiter__t.html',1,'']]],
  ['rocksdb_5freadoptions_5ft_6520',['rocksdb_readoptions_t',['../structrocksdb__readoptions__t.html',1,'']]],
  ['rocksdb_5frestore_5foptions_5ft_6521',['rocksdb_restore_options_t',['../structrocksdb__restore__options__t.html',1,'']]],
  ['rocksdb_5fseqfile_5ft_6522',['rocksdb_seqfile_t',['../structrocksdb__seqfile__t.html',1,'']]],
  ['rocksdb_5fslicetransform_5ft_6523',['rocksdb_slicetransform_t',['../structrocksdb__slicetransform__t.html',1,'']]],
  ['rocksdb_5fsnapshot_5ft_6524',['rocksdb_snapshot_t',['../structrocksdb__snapshot__t.html',1,'']]],
  ['rocksdb_5fsstfilewriter_5ft_6525',['rocksdb_sstfilewriter_t',['../structrocksdb__sstfilewriter__t.html',1,'']]],
  ['rocksdb_5ft_6526',['rocksdb_t',['../structrocksdb__t.html',1,'']]],
  ['rocksdb_5ftransaction_5foptions_5ft_6527',['rocksdb_transaction_options_t',['../structrocksdb__transaction__options__t.html',1,'']]],
  ['rocksdb_5ftransaction_5ft_6528',['rocksdb_transaction_t',['../structrocksdb__transaction__t.html',1,'']]],
  ['rocksdb_5ftransactiondb_5foptions_5ft_6529',['rocksdb_transactiondb_options_t',['../structrocksdb__transactiondb__options__t.html',1,'']]],
  ['rocksdb_5ftransactiondb_5ft_6530',['rocksdb_transactiondb_t',['../structrocksdb__transactiondb__t.html',1,'']]],
  ['rocksdb_5funiversal_5fcompaction_5foptions_5ft_6531',['rocksdb_universal_compaction_options_t',['../structrocksdb__universal__compaction__options__t.html',1,'']]],
  ['rocksdb_5fwal_5fiterator_5ft_6532',['rocksdb_wal_iterator_t',['../structrocksdb__wal__iterator__t.html',1,'']]],
  ['rocksdb_5fwal_5freadoptions_5ft_6533',['rocksdb_wal_readoptions_t',['../structrocksdb__wal__readoptions__t.html',1,'']]],
  ['rocksdb_5fwritablefile_5ft_6534',['rocksdb_writablefile_t',['../structrocksdb__writablefile__t.html',1,'']]],
  ['rocksdb_5fwritebatch_5ft_6535',['rocksdb_writebatch_t',['../structrocksdb__writebatch__t.html',1,'']]],
  ['rocksdb_5fwritebatch_5fwi_5ft_6536',['rocksdb_writebatch_wi_t',['../structrocksdb__writebatch__wi__t.html',1,'']]],
  ['rocksdb_5fwriteoptions_5ft_6537',['rocksdb_writeoptions_t',['../structrocksdb__writeoptions__t.html',1,'']]],
  ['rocksdbcolumnfamilysample_6538',['RocksDBColumnFamilySample',['../classRocksDBColumnFamilySample.html',1,'']]],
  ['rocksdbexception_6539',['RocksDBException',['../classorg_1_1rocksdb_1_1RocksDBException.html',1,'org::rocksdb']]],
  ['rocksdbexceptionjni_6540',['RocksDBExceptionJni',['../classROCKSDB__NAMESPACE_1_1RocksDBExceptionJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbexceptiontest_6541',['RocksDBExceptionTest',['../classorg_1_1rocksdb_1_1RocksDBExceptionTest.html',1,'org::rocksdb']]],
  ['rocksdbjni_6542',['RocksDBJni',['../classROCKSDB__NAMESPACE_1_1RocksDBJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_6543',['RocksDBNativeClass',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3acompactionfilterfactoryjnicallback_20_2a_2c_20abstractcompactionfilterfactoryjni_20_3e_6544',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::CompactionFilterFactoryJniCallback *, AbstractCompactionFilterFactoryJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3acomparatorjnicallback_20_2a_2c_20abstractcomparatorjni_20_3e_6545',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::ComparatorJniCallback *, AbstractComparatorJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3aeventlistenerjnicallback_20_2a_2c_20abstracteventlistenerjni_20_3e_6546',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::EventListenerJniCallback *, AbstractEventListenerJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3aslice_20_2a_2c_20abstractslicejni_20_3e_6547',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::Slice *, AbstractSliceJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3atablefilterjnicallback_20_2a_2c_20abstracttablefilterjni_20_3e_6548',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::TableFilterJniCallback *, AbstractTableFilterJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3atracewriterjnicallback_20_2a_2c_20abstracttracewriterjni_20_3e_6549',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::TraceWriterJniCallback *, AbstractTraceWriterJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3atransactionnotifierjnicallback_20_2a_2c_20abstracttransactionnotifierjni_20_3e_6550',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::TransactionNotifierJniCallback *, AbstractTransactionNotifierJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3awalfilterjnicallback_20_2a_2c_20abstractwalfilterjni_20_3e_6551',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::WalFilterJniCallback *, AbstractWalFilterJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20const_20rocksdb_5fnamespace_3a_3awritebatchhandlerjnicallback_20_2a_2c_20writebatchhandlerjni_20_3e_6552',['RocksDBNativeClass&lt; const ROCKSDB_NAMESPACE::WriteBatchHandlerJniCallback *, WriteBatchHandlerJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3abackupabledboptions_20_2a_2c_20backupabledboptionsjni_20_3e_6553',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::BackupableDBOptions *, BackupableDBOptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3abackupengine_20_2a_2c_20backupenginejni_20_3e_6554',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::BackupEngine *, BackupEngineJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3acolumnfamilyhandle_20_2a_2c_20columnfamilyhandlejni_20_3e_6555',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::ColumnFamilyHandle *, ColumnFamilyHandleJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3acolumnfamilyoptions_20_2a_2c_20columnfamilyoptionsjni_20_3e_6556',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::ColumnFamilyOptions *, ColumnFamilyOptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3acomparatorjnicallbackoptions_20_2a_2c_20comparatoroptionsjni_20_3e_6557',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::ComparatorJniCallbackOptions *, ComparatorOptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3adb_20_2a_2c_20rocksdbjni_20_3e_6558',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::DB *, RocksDBJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3adboptions_20_2a_2c_20dboptionsjni_20_3e_6559',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::DBOptions *, DBOptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3aflushoptions_20_2a_2c_20flushoptionsjni_20_3e_6560',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::FlushOptions *, FlushOptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3aiterator_20_2a_2c_20iteratorjni_20_3e_6561',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::Iterator *, IteratorJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3aoptions_20_2a_2c_20optionsjni_20_3e_6562',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::Options *, OptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3areadoptions_20_2a_2c_20readoptionsjni_20_3e_6563',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::ReadOptions *, ReadOptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3astatus_20_2a_2c_20statusjni_20_3e_6564',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::Status *, StatusJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3awritebatch_20_2a_2c_20writebatchjni_20_3e_6565',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::WriteBatch *, WriteBatchJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3awritebatchwithindex_20_2a_2c_20writebatchwithindexjni_20_3e_6566',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::WriteBatchWithIndex *, WriteBatchWithIndexJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20rocksdb_5fnamespace_3a_3awriteoptions_20_2a_2c_20writeoptionsjni_20_3e_6567',['RocksDBNativeClass&lt; ROCKSDB_NAMESPACE::WriteOptions *, WriteOptionsJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20std_3a_3ashared_5fptr_3c_20rocksdb_5fnamespace_3a_3afilterpolicy_20_3e_20_2a_2c_20filterjni_20_3e_6568',['RocksDBNativeClass&lt; std::shared_ptr&lt; ROCKSDB_NAMESPACE::FilterPolicy &gt; *, FilterJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbnativeclass_3c_20std_3a_3ashared_5fptr_3c_20rocksdb_5fnamespace_3a_3aloggerjnicallback_20_3e_20_2a_2c_20loggerjni_20_3e_6569',['RocksDBNativeClass&lt; std::shared_ptr&lt; ROCKSDB_NAMESPACE::LoggerJniCallback &gt; *, LoggerJni &gt;',['../classROCKSDB__NAMESPACE_1_1RocksDBNativeClass.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdboptionsparser_6570',['RocksDBOptionsParser',['../classROCKSDB__NAMESPACE_1_1RocksDBOptionsParser.html',1,'ROCKSDB_NAMESPACE']]],
  ['rocksdbsample_6571',['RocksDBSample',['../classRocksDBSample.html',1,'']]],
  ['rocksdbtest_6572',['RocksDBTest',['../classorg_1_1rocksdb_1_1RocksDBTest.html',1,'org::rocksdb']]],
  ['rocksenv_6573',['RocksEnv',['../classorg_1_1rocksdb_1_1RocksEnv.html',1,'org::rocksdb']]],
  ['rocksiterator_6574',['RocksIterator',['../classorg_1_1rocksdb_1_1RocksIterator.html',1,'org::rocksdb']]],
  ['rocksiteratorinterface_6575',['RocksIteratorInterface',['../interfaceorg_1_1rocksdb_1_1RocksIteratorInterface.html',1,'org::rocksdb']]],
  ['rocksiteratortest_6576',['RocksIteratorTest',['../classorg_1_1rocksdb_1_1RocksIteratorTest.html',1,'org::rocksdb']]],
  ['rocksjunitrunner_6577',['RocksJunitRunner',['../classorg_1_1rocksdb_1_1test_1_1RocksJunitRunner.html',1,'org::rocksdb::test']]],
  ['rocksmemenv_6578',['RocksMemEnv',['../classorg_1_1rocksdb_1_1RocksMemEnv.html',1,'org::rocksdb']]],
  ['rocksmemenvtest_6579',['RocksMemEnvTest',['../classorg_1_1rocksdb_1_1RocksMemEnvTest.html',1,'org::rocksdb']]],
  ['rocksmutableobject_6580',['RocksMutableObject',['../classorg_1_1rocksdb_1_1RocksMutableObject.html',1,'org::rocksdb']]],
  ['rocksnativelibraryresource_6581',['RocksNativeLibraryResource',['../classorg_1_1rocksdb_1_1RocksNativeLibraryResource.html',1,'org::rocksdb']]],
  ['rocksobject_6582',['RocksObject',['../classorg_1_1rocksdb_1_1RocksObject.html',1,'org::rocksdb']]],
  ['row_5flock_6583',['row_lock',['../structtoku_1_1row__lock.html',1,'toku']]],
  ['rowvalue_6584',['RowValue',['../classROCKSDB__NAMESPACE_1_1cassandra_1_1RowValue.html',1,'ROCKSDB_NAMESPACE::cassandra']]],
  ['rowvaluemergetest_6585',['RowValueMergeTest',['../classROCKSDB__NAMESPACE_1_1cassandra_1_1RowValueMergeTest.html',1,'ROCKSDB_NAMESPACE::cassandra']]],
  ['rowvaluetest_6586',['RowValueTest',['../classROCKSDB__NAMESPACE_1_1cassandra_1_1RowValueTest.html',1,'ROCKSDB_NAMESPACE::cassandra']]],
  ['rule_6587',['Rule',['../classadvisor_1_1rule__parser_1_1Rule.html',1,'advisor::rule_parser']]],
  ['rulesspec_6588',['RulesSpec',['../classadvisor_1_1rule__parser_1_1RulesSpec.html',1,'advisor::rule_parser']]],
  ['runtimeorder_6589',['RunTimeOrder',['../structROCKSDB__NAMESPACE_1_1Timer_1_1RunTimeOrder.html',1,'ROCKSDB_NAMESPACE::Timer']]],
  ['rvalueref_6590',['RvalueRef',['../structtesting_1_1internal_1_1RvalueRef.html',1,'testing::internal']]],
  ['rwmutex_6591',['RWMutex',['../classROCKSDB__NAMESPACE_1_1port_1_1RWMutex.html',1,'ROCKSDB_NAMESPACE::port']]]
];
