var searchData=
[
  ['samesizetupleprefixcomparator_6592',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e_6593',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e_6594',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['sanitylevel_6595',['SanityLevel',['../enumorg_1_1rocksdb_1_1SanityLevel.html',1,'org::rocksdb']]],
  ['sanityleveljni_6596',['SanityLevelJni',['../classROCKSDB__NAMESPACE_1_1SanityLevelJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytest_6597',['SanityTest',['../classROCKSDB__NAMESPACE_1_1SanityTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestbasic_6598',['SanityTestBasic',['../classROCKSDB__NAMESPACE_1_1SanityTestBasic.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestbloomfilter_6599',['SanityTestBloomFilter',['../classROCKSDB__NAMESPACE_1_1SanityTestBloomFilter.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestlz4compression_6600',['SanityTestLZ4Compression',['../classROCKSDB__NAMESPACE_1_1SanityTestLZ4Compression.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestlz4hccompression_6601',['SanityTestLZ4HCCompression',['../classROCKSDB__NAMESPACE_1_1SanityTestLZ4HCCompression.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestplaintablefactory_6602',['SanityTestPlainTableFactory',['../classROCKSDB__NAMESPACE_1_1SanityTestPlainTableFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestspecialcomparator_6603',['SanityTestSpecialComparator',['../classROCKSDB__NAMESPACE_1_1SanityTestSpecialComparator.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestzlibcompression_6604',['SanityTestZlibCompression',['../classROCKSDB__NAMESPACE_1_1SanityTestZlibCompression.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestzlibcompressionversion2_6605',['SanityTestZlibCompressionVersion2',['../classROCKSDB__NAMESPACE_1_1SanityTestZlibCompressionVersion2.html',1,'ROCKSDB_NAMESPACE']]],
  ['sanitytestzstdcompression_6606',['SanityTestZSTDCompression',['../classROCKSDB__NAMESPACE_1_1SanityTestZSTDCompression.html',1,'ROCKSDB_NAMESPACE']]],
  ['saveandrestore_6607',['SaveAndRestore',['../classROCKSDB__NAMESPACE_1_1SaveAndRestore.html',1,'ROCKSDB_NAMESPACE']]],
  ['savepoint_6608',['SavePoint',['../classorg_1_1rocksdb_1_1WriteBatch_1_1SavePoint.html',1,'org.rocksdb.WriteBatch.SavePoint'],['../structROCKSDB__NAMESPACE_1_1SavePoint.html',1,'ROCKSDB_NAMESPACE::SavePoint'],['../structROCKSDB__NAMESPACE_1_1TransactionBaseImpl_1_1SavePoint.html',1,'ROCKSDB_NAMESPACE::TransactionBaseImpl::SavePoint'],['../structROCKSDB__NAMESPACE_1_1WriteUnpreparedTxn_1_1SavePoint.html',1,'ROCKSDB_NAMESPACE::WriteUnpreparedTxn::SavePoint']]],
  ['savepoints_6609',['SavePoints',['../structROCKSDB__NAMESPACE_1_1SavePoints.html',1,'ROCKSDB_NAMESPACE']]],
  ['scanbuilderrorparser_6610',['ScanBuildErrorParser',['../classerror__filter_1_1ScanBuildErrorParser.html',1,'error_filter']]],
  ['scancommand_6611',['ScanCommand',['../classROCKSDB__NAMESPACE_1_1ScanCommand.html',1,'ROCKSDB_NAMESPACE']]],
  ['scoped_5fptr_6612',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e_6613',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e_6614',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20t_20_3e_6615',['scoped_ptr&lt; const T &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20gtest_5fflag_5fsaver_5f_20_3e_6616',['scoped_ptr&lt; GTEST_FLAG_SAVER_ &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3aparamiteratorinterface_3c_20t_20_3e_20_3e_6617',['scoped_ptr&lt; testing::internal::ParamIteratorInterface&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3atestmetafactorybase_3c_20paramtype_20_3e_20_3e_6618',['scoped_ptr&lt; testing::internal::TestMetaFactoryBase&lt; ParamType &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedarenaiterator_6619',['ScopedArenaIterator',['../classROCKSDB__NAMESPACE_1_1ScopedArenaIterator.html',1,'ROCKSDB_NAMESPACE']]],
  ['scopedtrace_6620',['ScopedTrace',['../classtesting_1_1ScopedTrace.html',1,'testing']]],
  ['scopeguardimpl_6621',['ScopeGuardImpl',['../classfolly_1_1scope__guard__detail_1_1ScopeGuardImpl.html',1,'folly::scope_guard_detail']]],
  ['secondarycache_6622',['SecondaryCache',['../classROCKSDB__NAMESPACE_1_1SecondaryCache.html',1,'ROCKSDB_NAMESPACE']]],
  ['secondarycacheresulthandle_6623',['SecondaryCacheResultHandle',['../classROCKSDB__NAMESPACE_1_1SecondaryCacheResultHandle.html',1,'ROCKSDB_NAMESPACE']]],
  ['secondarydbtest_6624',['SecondaryDBTest',['../classorg_1_1rocksdb_1_1SecondaryDBTest.html',1,'org::rocksdb']]],
  ['section_6625',['Section',['../classadvisor_1_1rule__parser_1_1Section.html',1,'advisor::rule_parser']]],
  ['segment_6626',['Segment',['../classorg_1_1rocksdb_1_1RocksDBTest_1_1Segment.html',1,'org::rocksdb::RocksDBTest']]],
  ['semistructureduniqueidgen_6627',['SemiStructuredUniqueIdGen',['../classROCKSDB__NAMESPACE_1_1SemiStructuredUniqueIdGen.html',1,'ROCKSDB_NAMESPACE']]],
  ['seqadvanceconcurrenttest_6628',['SeqAdvanceConcurrentTest',['../classROCKSDB__NAMESPACE_1_1SeqAdvanceConcurrentTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['seqmaxcomparator_6629',['SeqMaxComparator',['../structROCKSDB__NAMESPACE_1_1SeqMaxComparator.html',1,'ROCKSDB_NAMESPACE']]],
  ['seqstringsource_6630',['SeqStringSource',['../classROCKSDB__NAMESPACE_1_1test_1_1SeqStringSource.html',1,'ROCKSDB_NAMESPACE::test']]],
  ['sequenceiterwrapper_6631',['SequenceIterWrapper',['../classROCKSDB__NAMESPACE_1_1SequenceIterWrapper.html',1,'ROCKSDB_NAMESPACE']]],
  ['sequentialfile_6632',['SequentialFile',['../classROCKSDB__NAMESPACE_1_1SequentialFile.html',1,'ROCKSDB_NAMESPACE']]],
  ['sequentialfilemirror_6633',['SequentialFileMirror',['../classROCKSDB__NAMESPACE_1_1SequentialFileMirror.html',1,'ROCKSDB_NAMESPACE']]],
  ['sequentialfilereader_6634',['SequentialFileReader',['../classROCKSDB__NAMESPACE_1_1SequentialFileReader.html',1,'ROCKSDB_NAMESPACE']]],
  ['sequentialfilewrapper_6635',['SequentialFileWrapper',['../classROCKSDB__NAMESPACE_1_1SequentialFileWrapper.html',1,'ROCKSDB_NAMESPACE']]],
  ['serializableinterleavedsolution_6636',['SerializableInterleavedSolution',['../classROCKSDB__NAMESPACE_1_1ribbon_1_1SerializableInterleavedSolution.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['setcomparator_6637',['SetComparator',['../structROCKSDB__NAMESPACE_1_1SetComparator.html',1,'ROCKSDB_NAMESPACE']]],
  ['setup_5fshould_5fbe_5fspelled_5fsetup_6638',['Setup_should_be_spelled_SetUp',['../structtesting_1_1Test_1_1Setup__should__be__spelled__SetUp.html',1,'testing::Test::Setup_should_be_spelled_SetUp'],['../structtesting_1_1Environment_1_1Setup__should__be__spelled__SetUp.html',1,'testing::Environment::Setup_should_be_spelled_SetUp']]],
  ['shard_6639',['Shard',['../structROCKSDB__NAMESPACE_1_1ConcurrentArena_1_1Shard.html',1,'ROCKSDB_NAMESPACE::ConcurrentArena']]],
  ['shardedcache_6640',['ShardedCache',['../classROCKSDB__NAMESPACE_1_1ShardedCache.html',1,'ROCKSDB_NAMESPACE']]],
  ['sharedblobfilemetadata_6641',['SharedBlobFileMetaData',['../classROCKSDB__NAMESPACE_1_1SharedBlobFileMetaData.html',1,'ROCKSDB_NAMESPACE']]],
  ['shortenedindexbuilder_6642',['ShortenedIndexBuilder',['../classROCKSDB__NAMESPACE_1_1ShortenedIndexBuilder.html',1,'ROCKSDB_NAMESPACE']]],
  ['simcache_6643',['SimCache',['../classROCKSDB__NAMESPACE_1_1SimCache.html',1,'ROCKSDB_NAMESPACE']]],
  ['simcachetest_6644',['SimCacheTest',['../classROCKSDB__NAMESPACE_1_1SimCacheTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['simple_5fdbt_6645',['simple_dbt',['../structsimple__dbt.html',1,'']]],
  ['simpleconfigurable_6646',['SimpleConfigurable',['../classROCKSDB__NAMESPACE_1_1test_1_1SimpleConfigurable.html',1,'ROCKSDB_NAMESPACE::test']]],
  ['simplesuffixreversecomparator_6647',['SimpleSuffixReverseComparator',['../classROCKSDB__NAMESPACE_1_1test_1_1SimpleSuffixReverseComparator.html',1,'ROCKSDB_NAMESPACE::test']]],
  ['simulatedhybridfilesystem_6648',['SimulatedHybridFileSystem',['../classROCKSDB__NAMESPACE_1_1SimulatedHybridFileSystem.html',1,'ROCKSDB_NAMESPACE']]],
  ['simulatedhybridraf_6649',['SimulatedHybridRaf',['../classROCKSDB__NAMESPACE_1_1SimulatedHybridRaf.html',1,'ROCKSDB_NAMESPACE']]],
  ['singleallocator_6650',['SingleAllocator',['../classROCKSDB__NAMESPACE_1_1SingleAllocator.html',1,'ROCKSDB_NAMESPACE']]],
  ['singlevaluetraceexecutionresult_6651',['SingleValueTraceExecutionResult',['../classROCKSDB__NAMESPACE_1_1SingleValueTraceExecutionResult.html',1,'ROCKSDB_NAMESPACE']]],
  ['sizeapproximationflag_6652',['SizeApproximationFlag',['../enumorg_1_1rocksdb_1_1SizeApproximationFlag.html',1,'org::rocksdb']]],
  ['sizeapproximationoptions_6653',['SizeApproximationOptions',['../structROCKSDB__NAMESPACE_1_1SizeApproximationOptions.html',1,'ROCKSDB_NAMESPACE']]],
  ['sizeof_6654',['Sizeof',['../structfolly_1_1detail_1_1distributed__mutex_1_1Sizeof.html',1,'folly::detail::distributed_mutex']]],
  ['sizeof_5f_6655',['Sizeof_',['../structfolly_1_1detail_1_1distributed__mutex_1_1Sizeof__.html',1,'folly::detail::distributed_mutex']]],
  ['sizeof_5f_3c_20t_2c_20false_20_3e_6656',['Sizeof_&lt; T, false &gt;',['../structfolly_1_1detail_1_1distributed__mutex_1_1Sizeof___3_01T_00_01false_01_4.html',1,'folly::detail::distributed_mutex']]],
  ['sizeof_5f_3c_20t_2c_20std_3a_3ais_5fvoid_3c_20t_20_3e_3a_3avalue_20_3e_6657',['Sizeof_&lt; T, std::is_void&lt; T &gt;::value &gt;',['../structfolly_1_1detail_1_1distributed__mutex_1_1Sizeof__.html',1,'folly::detail::distributed_mutex']]],
  ['sizeof_5f_3c_20t_2c_20true_20_3e_6658',['Sizeof_&lt; T, true &gt;',['../structfolly_1_1detail_1_1distributed__mutex_1_1Sizeof___3_01T_00_01true_01_4.html',1,'folly::detail::distributed_mutex']]],
  ['sizeunit_6659',['SizeUnit',['../classorg_1_1rocksdb_1_1util_1_1SizeUnit.html',1,'org::rocksdb::util']]],
  ['sizeunittest_6660',['SizeUnitTest',['../classorg_1_1rocksdb_1_1util_1_1SizeUnitTest.html',1,'org::rocksdb::util']]],
  ['skipevenfilter_6661',['SkipEvenFilter',['../classROCKSDB__NAMESPACE_1_1SkipEvenFilter.html',1,'ROCKSDB_NAMESPACE']]],
  ['skipevenfilterfactory_6662',['SkipEvenFilterFactory',['../classROCKSDB__NAMESPACE_1_1SkipEvenFilterFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['skiplist_6663',['SkipList',['../classROCKSDB__NAMESPACE_1_1SkipList.html',1,'ROCKSDB_NAMESPACE']]],
  ['skiplist_3c_20key_2c_20rocksdb_5fnamespace_3a_3atestcomparator_20_3e_6664',['SkipList&lt; Key, ROCKSDB_NAMESPACE::TestComparator &gt;',['../classROCKSDB__NAMESPACE_1_1SkipList.html',1,'ROCKSDB_NAMESPACE']]],
  ['skiplist_3c_20writebatchindexentry_20_2a_2c_20const_20writebatchentrycomparator_20_26_20_3e_6665',['SkipList&lt; WriteBatchIndexEntry *, const WriteBatchEntryComparator &amp; &gt;',['../classROCKSDB__NAMESPACE_1_1SkipList.html',1,'ROCKSDB_NAMESPACE']]],
  ['skiplistfactory_6666',['SkipListFactory',['../classROCKSDB__NAMESPACE_1_1SkipListFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['skiplistmemtableconfig_6667',['SkipListMemTableConfig',['../classorg_1_1rocksdb_1_1SkipListMemTableConfig.html',1,'org::rocksdb']]],
  ['skiptest_6668',['SkipTest',['../classROCKSDB__NAMESPACE_1_1SkipTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['sleeper_6669',['Sleeper',['../classfolly_1_1detail_1_1Sleeper.html',1,'folly::detail']]],
  ['sleepingbackgroundtask_6670',['SleepingBackgroundTask',['../classROCKSDB__NAMESPACE_1_1test_1_1SleepingBackgroundTask.html',1,'ROCKSDB_NAMESPACE::test']]],
  ['slice_6671',['Slice',['../classorg_1_1rocksdb_1_1Slice.html',1,'org.rocksdb.Slice'],['../classROCKSDB__NAMESPACE_1_1Slice.html',1,'ROCKSDB_NAMESPACE::Slice']]],
  ['sliceformatter_6672',['SliceFormatter',['../classROCKSDB__NAMESPACE_1_1SliceFormatter.html',1,'ROCKSDB_NAMESPACE']]],
  ['slicehasher_6673',['SliceHasher',['../structROCKSDB__NAMESPACE_1_1SliceHasher.html',1,'ROCKSDB_NAMESPACE']]],
  ['slicejni_6674',['SliceJni',['../classROCKSDB__NAMESPACE_1_1SliceJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['sliceparts_6675',['SliceParts',['../structROCKSDB__NAMESPACE_1_1SliceParts.html',1,'ROCKSDB_NAMESPACE']]],
  ['slicetest_6676',['SliceTest',['../classorg_1_1rocksdb_1_1SliceTest.html',1,'org::rocksdb']]],
  ['slicetransform_6677',['SliceTransform',['../classROCKSDB__NAMESPACE_1_1SliceTransform.html',1,'ROCKSDB_NAMESPACE']]],
  ['slicetransformdbtest_6678',['SliceTransformDBTest',['../classROCKSDB__NAMESPACE_1_1SliceTransformDBTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['slicetransformlimiteddomain_6679',['SliceTransformLimitedDomain',['../classROCKSDB__NAMESPACE_1_1SliceTransformLimitedDomain.html',1,'ROCKSDB_NAMESPACE']]],
  ['slicetransformlimiteddomaingeneric_6680',['SliceTransformLimitedDomainGeneric',['../classROCKSDB__NAMESPACE_1_1SliceTransformLimitedDomainGeneric.html',1,'ROCKSDB_NAMESPACE']]],
  ['slicetransformtest_6681',['SliceTransformTest',['../classROCKSDB__NAMESPACE_1_1SliceTransformTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['smallenumset_6682',['SmallEnumSet',['../classROCKSDB__NAMESPACE_1_1SmallEnumSet.html',1,'ROCKSDB_NAMESPACE']]],
  ['smallenumset_3c_20filetype_2c_20filetype_3a_3akblobfile_20_3e_6683',['SmallEnumSet&lt; FileType, FileType::kBlobFile &gt;',['../classROCKSDB__NAMESPACE_1_1SmallEnumSet.html',1,'ROCKSDB_NAMESPACE']]],
  ['smallenumsettest_6684',['SmallEnumSetTest',['../classROCKSDB__NAMESPACE_1_1SmallEnumSetTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['snapshot_6685',['Snapshot',['../classROCKSDB__NAMESPACE_1_1Snapshot.html',1,'ROCKSDB_NAMESPACE::Snapshot'],['../classorg_1_1rocksdb_1_1Snapshot.html',1,'org.rocksdb.Snapshot']]],
  ['snapshotchecker_6686',['SnapshotChecker',['../classROCKSDB__NAMESPACE_1_1SnapshotChecker.html',1,'ROCKSDB_NAMESPACE']]],
  ['snapshotconcurrentaccesstest_6687',['SnapshotConcurrentAccessTest',['../classROCKSDB__NAMESPACE_1_1SnapshotConcurrentAccessTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['snapshotimpl_6688',['SnapshotImpl',['../classROCKSDB__NAMESPACE_1_1SnapshotImpl.html',1,'ROCKSDB_NAMESPACE']]],
  ['snapshotlist_6689',['SnapshotList',['../classROCKSDB__NAMESPACE_1_1SnapshotList.html',1,'ROCKSDB_NAMESPACE']]],
  ['snapshottest_6690',['SnapshotTest',['../classorg_1_1rocksdb_1_1SnapshotTest.html',1,'org::rocksdb']]],
  ['socketacceptexception_6691',['SocketAcceptException',['../classffd_1_1SocketAcceptException.html',1,'ffd']]],
  ['socketaddressexception_6692',['SocketAddressException',['../classffd_1_1SocketAddressException.html',1,'ffd']]],
  ['socketbase_6693',['SocketBase',['../classffd_1_1SocketBase.html',1,'ffd']]],
  ['socketbindexception_6694',['SocketBindException',['../classffd_1_1SocketBindException.html',1,'ffd']]],
  ['socketcloseexception_6695',['SocketCloseException',['../classffd_1_1SocketCloseException.html',1,'ffd']]],
  ['socketconnectexception_6696',['SocketConnectException',['../classffd_1_1SocketConnectException.html',1,'ffd']]],
  ['socketcreateexception_6697',['SocketCreateException',['../classffd_1_1SocketCreateException.html',1,'ffd']]],
  ['socketexception_6698',['SocketException',['../classffd_1_1SocketException.html',1,'ffd']]],
  ['socketlistenexception_6699',['SocketListenException',['../classffd_1_1SocketListenException.html',1,'ffd']]],
  ['socketreadexception_6700',['SocketReadException',['../classffd_1_1SocketReadException.html',1,'ffd']]],
  ['socketshutdownexception_6701',['SocketShutdownException',['../classffd_1_1SocketShutdownException.html',1,'ffd']]],
  ['socketwriteexception_6702',['SocketWriteException',['../classffd_1_1SocketWriteException.html',1,'ffd']]],
  ['sortlist_6703',['SortList',['../classROCKSDB__NAMESPACE_1_1SortList.html',1,'ROCKSDB_NAMESPACE']]],
  ['specialenv_6704',['SpecialEnv',['../classROCKSDB__NAMESPACE_1_1SpecialEnv.html',1,'ROCKSDB_NAMESPACE']]],
  ['specialtimeenv_6705',['SpecialTimeEnv',['../classROCKSDB__NAMESPACE_1_1SpecialTimeEnv.html',1,'ROCKSDB_NAMESPACE']]],
  ['spinmutex_6706',['SpinMutex',['../classROCKSDB__NAMESPACE_1_1SpinMutex.html',1,'ROCKSDB_NAMESPACE']]],
  ['splice_6707',['Splice',['../structROCKSDB__NAMESPACE_1_1InlineSkipList_1_1Splice.html',1,'ROCKSDB_NAMESPACE::InlineSkipList']]],
  ['sstdumptool_6708',['SSTDumpTool',['../classROCKSDB__NAMESPACE_1_1SSTDumpTool.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstdumptooltest_6709',['SSTDumpToolTest',['../classROCKSDB__NAMESPACE_1_1SSTDumpToolTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfileaccessinfoaggregate_6710',['SSTFileAccessInfoAggregate',['../structROCKSDB__NAMESPACE_1_1SSTFileAccessInfoAggregate.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfiledumper_6711',['SstFileDumper',['../classROCKSDB__NAMESPACE_1_1SstFileDumper.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilemanager_6712',['SstFileManager',['../classROCKSDB__NAMESPACE_1_1SstFileManager.html',1,'ROCKSDB_NAMESPACE::SstFileManager'],['../classorg_1_1rocksdb_1_1SstFileManager.html',1,'org.rocksdb.SstFileManager']]],
  ['sstfilemanagerimpl_6713',['SstFileManagerImpl',['../classROCKSDB__NAMESPACE_1_1SstFileManagerImpl.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilemanagertest_6714',['SstFileManagerTest',['../classorg_1_1rocksdb_1_1SstFileManagerTest.html',1,'org::rocksdb']]],
  ['sstfilemetadata_6715',['SstFileMetaData',['../structROCKSDB__NAMESPACE_1_1SstFileMetaData.html',1,'ROCKSDB_NAMESPACE::SstFileMetaData'],['../classorg_1_1rocksdb_1_1SstFileMetaData.html',1,'org.rocksdb.SstFileMetaData']]],
  ['sstfilemetadatajni_6716',['SstFileMetaDataJni',['../classROCKSDB__NAMESPACE_1_1SstFileMetaDataJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilereader_6717',['SstFileReader',['../classorg_1_1rocksdb_1_1SstFileReader.html',1,'org.rocksdb.SstFileReader'],['../classROCKSDB__NAMESPACE_1_1SstFileReader.html',1,'ROCKSDB_NAMESPACE::SstFileReader']]],
  ['sstfilereaderiterator_6718',['SstFileReaderIterator',['../classorg_1_1rocksdb_1_1SstFileReaderIterator.html',1,'org::rocksdb']]],
  ['sstfilereadertest_6719',['SstFileReaderTest',['../classROCKSDB__NAMESPACE_1_1SstFileReaderTest.html',1,'ROCKSDB_NAMESPACE::SstFileReaderTest'],['../classorg_1_1rocksdb_1_1SstFileReaderTest.html',1,'org.rocksdb.SstFileReaderTest']]],
  ['sstfilereadertimestamptest_6720',['SstFileReaderTimestampTest',['../classROCKSDB__NAMESPACE_1_1SstFileReaderTimestampTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilewriter_6721',['SstFileWriter',['../classorg_1_1rocksdb_1_1SstFileWriter.html',1,'org.rocksdb.SstFileWriter'],['../classROCKSDB__NAMESPACE_1_1SstFileWriter.html',1,'ROCKSDB_NAMESPACE::SstFileWriter']]],
  ['sstfilewritercollector_6722',['SstFileWriterCollector',['../classROCKSDB__NAMESPACE_1_1SstFileWriterCollector.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilewritercollectorfactory_6723',['SstFileWriterCollectorFactory',['../classROCKSDB__NAMESPACE_1_1SstFileWriterCollectorFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilewriterpropertiescollector_6724',['SstFileWriterPropertiesCollector',['../classROCKSDB__NAMESPACE_1_1SstFileWriterPropertiesCollector.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilewriterpropertiescollectorfactory_6725',['SstFileWriterPropertiesCollectorFactory',['../classROCKSDB__NAMESPACE_1_1SstFileWriterPropertiesCollectorFactory.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstfilewritertest_6726',['SstFileWriterTest',['../classorg_1_1rocksdb_1_1SstFileWriterTest.html',1,'org::rocksdb']]],
  ['sstinfo_6727',['SstInfo',['../structROCKSDB__NAMESPACE_1_1VersionSetTestMissingFiles_1_1SstInfo.html',1,'ROCKSDB_NAMESPACE::VersionSetTestMissingFiles']]],
  ['sstpartitioner_6728',['SstPartitioner',['../classROCKSDB__NAMESPACE_1_1SstPartitioner.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstpartitionerfactory_6729',['SstPartitionerFactory',['../classorg_1_1rocksdb_1_1SstPartitionerFactory.html',1,'org.rocksdb.SstPartitionerFactory'],['../classROCKSDB__NAMESPACE_1_1SstPartitionerFactory.html',1,'ROCKSDB_NAMESPACE::SstPartitionerFactory']]],
  ['sstpartitionerfixedprefix_6730',['SstPartitionerFixedPrefix',['../classROCKSDB__NAMESPACE_1_1SstPartitionerFixedPrefix.html',1,'ROCKSDB_NAMESPACE']]],
  ['sstpartitionerfixedprefixfactory_6731',['SstPartitionerFixedPrefixFactory',['../classorg_1_1rocksdb_1_1SstPartitionerFixedPrefixFactory.html',1,'org.rocksdb.SstPartitionerFixedPrefixFactory'],['../classROCKSDB__NAMESPACE_1_1SstPartitionerFixedPrefixFactory.html',1,'ROCKSDB_NAMESPACE::SstPartitionerFixedPrefixFactory']]],
  ['sstpartitionertest_6732',['SstPartitionerTest',['../classorg_1_1rocksdb_1_1SstPartitionerTest.html',1,'org::rocksdb']]],
  ['stablecachekeytestfs_6733',['StableCacheKeyTestFS',['../classROCKSDB__NAMESPACE_1_1StableCacheKeyTestFS.html',1,'ROCKSDB_NAMESPACE']]],
  ['stackabledb_6734',['StackableDB',['../classROCKSDB__NAMESPACE_1_1StackableDB.html',1,'ROCKSDB_NAMESPACE']]],
  ['stallingfilter_6735',['StallingFilter',['../classROCKSDB__NAMESPACE_1_1StallingFilter.html',1,'ROCKSDB_NAMESPACE']]],
  ['stallinterface_6736',['StallInterface',['../classROCKSDB__NAMESPACE_1_1StallInterface.html',1,'ROCKSDB_NAMESPACE']]],
  ['standardbanding_6737',['StandardBanding',['../classROCKSDB__NAMESPACE_1_1ribbon_1_1StandardBanding.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['standardhasher_6738',['StandardHasher',['../classROCKSDB__NAMESPACE_1_1ribbon_1_1StandardHasher.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['standardrehasheradapter_6739',['StandardRehasherAdapter',['../classROCKSDB__NAMESPACE_1_1ribbon_1_1StandardRehasherAdapter.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['standardrehasheradapter_3c_20abridgedtypesandsettings_20_3e_6740',['StandardRehasherAdapter&lt; AbridgedTypesAndSettings &gt;',['../classROCKSDB__NAMESPACE_1_1ribbon_1_1StandardRehasherAdapter.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['standardrehasheradapter_3c_20typesandsettings_5fhash32_20_3e_6741',['StandardRehasherAdapter&lt; TypesAndSettings_Hash32 &gt;',['../classROCKSDB__NAMESPACE_1_1ribbon_1_1StandardRehasherAdapter.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['standardrehasheradapter_3c_20typesandsettings_5fseed64_20_3e_6742',['StandardRehasherAdapter&lt; TypesAndSettings_Seed64 &gt;',['../classROCKSDB__NAMESPACE_1_1ribbon_1_1StandardRehasherAdapter.html',1,'ROCKSDB_NAMESPACE::ribbon']]],
  ['startkeymaxcomparator_6743',['StartKeyMaxComparator',['../structROCKSDB__NAMESPACE_1_1ReverseRangeDelIterator_1_1StartKeyMaxComparator.html',1,'ROCKSDB_NAMESPACE::ReverseRangeDelIterator']]],
  ['startkeymincomparator_6744',['StartKeyMinComparator',['../structROCKSDB__NAMESPACE_1_1StartKeyMinComparator.html',1,'ROCKSDB_NAMESPACE']]],
  ['state_6745',['State',['../structROCKSDB__NAMESPACE_1_1ConcurrentTest_1_1State.html',1,'ROCKSDB_NAMESPACE::ConcurrentTest::State'],['../structROCKSDB__NAMESPACE_1_1State.html',1,'ROCKSDB_NAMESPACE::State']]],
  ['stateinfo_6746',['StateInfo',['../structROCKSDB__NAMESPACE_1_1StateInfo.html',1,'ROCKSDB_NAMESPACE']]],
  ['statetype_6747',['StateType',['../enumorg_1_1rocksdb_1_1StateType.html',1,'org::rocksdb']]],
  ['statetypejni_6748',['StateTypeJni',['../classROCKSDB__NAMESPACE_1_1StateTypeJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['staticasserttypeeqhelper_6749',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e_6750',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper_3_01T_00_01T_01_4.html',1,'testing::internal']]],
  ['staticmeta_6751',['StaticMeta',['../classROCKSDB__NAMESPACE_1_1ThreadLocalPtr_1_1StaticMeta.html',1,'ROCKSDB_NAMESPACE::ThreadLocalPtr']]],
  ['statistics_6752',['Statistics',['../classorg_1_1rocksdb_1_1Statistics.html',1,'org.rocksdb.Statistics'],['../structROCKSDB__NAMESPACE_1_1BlockCacheTier_1_1Statistics.html',1,'ROCKSDB_NAMESPACE::BlockCacheTier::Statistics'],['../structROCKSDB__NAMESPACE_1_1VolatileCacheTier_1_1Statistics.html',1,'ROCKSDB_NAMESPACE::VolatileCacheTier::Statistics'],['../classROCKSDB__NAMESPACE_1_1Statistics.html',1,'ROCKSDB_NAMESPACE::Statistics']]],
  ['statisticscollector_6753',['StatisticsCollector',['../classorg_1_1rocksdb_1_1StatisticsCollector.html',1,'org::rocksdb']]],
  ['statisticscollectorcallback_6754',['StatisticsCollectorCallback',['../interfaceorg_1_1rocksdb_1_1StatisticsCollectorCallback.html',1,'org::rocksdb']]],
  ['statisticscollectortest_6755',['StatisticsCollectorTest',['../classorg_1_1rocksdb_1_1StatisticsCollectorTest.html',1,'org::rocksdb']]],
  ['statisticsimpl_6756',['StatisticsImpl',['../classROCKSDB__NAMESPACE_1_1StatisticsImpl.html',1,'ROCKSDB_NAMESPACE']]],
  ['statisticsjni_6757',['StatisticsJni',['../classROCKSDB__NAMESPACE_1_1StatisticsJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['statisticstest_6758',['StatisticsTest',['../classROCKSDB__NAMESPACE_1_1StatisticsTest.html',1,'ROCKSDB_NAMESPACE::StatisticsTest'],['../classorg_1_1rocksdb_1_1StatisticsTest.html',1,'org.rocksdb.StatisticsTest']]],
  ['stats_6759',['Stats',['../classROCKSDB__NAMESPACE_1_1Stats.html',1,'ROCKSDB_NAMESPACE']]],
  ['statscallbackmock_6760',['StatsCallbackMock',['../classorg_1_1rocksdb_1_1StatsCallbackMock.html',1,'org::rocksdb']]],
  ['statscollectorinput_6761',['StatsCollectorInput',['../classorg_1_1rocksdb_1_1StatsCollectorInput.html',1,'org::rocksdb']]],
  ['statshistoryiterator_6762',['StatsHistoryIterator',['../classROCKSDB__NAMESPACE_1_1StatsHistoryIterator.html',1,'ROCKSDB_NAMESPACE']]],
  ['statshistorytest_6763',['StatsHistoryTest',['../classROCKSDB__NAMESPACE_1_1StatsHistoryTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['statslevel_6764',['StatsLevel',['../enumorg_1_1rocksdb_1_1StatsLevel.html',1,'org::rocksdb']]],
  ['statsleveljni_6765',['StatsLevelJni',['../classROCKSDB__NAMESPACE_1_1StatsLevelJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['statsunit_6766',['StatsUnit',['../structROCKSDB__NAMESPACE_1_1StatsUnit.html',1,'ROCKSDB_NAMESPACE']]],
  ['status_6767',['Status',['../classorg_1_1rocksdb_1_1Status.html',1,'org.rocksdb.Status'],['../classROCKSDB__NAMESPACE_1_1Status.html',1,'ROCKSDB_NAMESPACE::Status']]],
  ['statusjni_6768',['StatusJni',['../classROCKSDB__NAMESPACE_1_1StatusJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['statusonlytraceexecutionresult_6769',['StatusOnlyTraceExecutionResult',['../classROCKSDB__NAMESPACE_1_1StatusOnlyTraceExecutionResult.html',1,'ROCKSDB_NAMESPACE']]],
  ['stderrlogger_6770',['StderrLogger',['../classROCKSDB__NAMESPACE_1_1StderrLogger.html',1,'ROCKSDB_NAMESPACE']]],
  ['stopwatch_6771',['StopWatch',['../classROCKSDB__NAMESPACE_1_1StopWatch.html',1,'ROCKSDB_NAMESPACE']]],
  ['stopwatchnano_6772',['StopWatchNano',['../classROCKSDB__NAMESPACE_1_1StopWatchNano.html',1,'ROCKSDB_NAMESPACE']]],
  ['stopwritetoken_6773',['StopWriteToken',['../classROCKSDB__NAMESPACE_1_1StopWriteToken.html',1,'ROCKSDB_NAMESPACE']]],
  ['storage_6774',['Storage',['../unionfolly_1_1Indestructible_1_1Storage.html',1,'folly::Indestructible']]],
  ['storagenontriviallydestructible_6775',['StorageNonTriviallyDestructible',['../structfolly_1_1Optional_1_1StorageNonTriviallyDestructible.html',1,'folly::Optional']]],
  ['storagetriviallydestructible_6776',['StorageTriviallyDestructible',['../structfolly_1_1Optional_1_1StorageTriviallyDestructible.html',1,'folly::Optional']]],
  ['stringappendoperator_6777',['StringAppendOperator',['../classorg_1_1rocksdb_1_1StringAppendOperator.html',1,'org.rocksdb.StringAppendOperator'],['../classROCKSDB__NAMESPACE_1_1StringAppendOperator.html',1,'ROCKSDB_NAMESPACE::StringAppendOperator']]],
  ['stringappendoperatortest_6778',['StringAppendOperatorTest',['../classROCKSDB__NAMESPACE_1_1StringAppendOperatorTest.html',1,'ROCKSDB_NAMESPACE']]],
  ['stringappendtestoperator_6779',['StringAppendTESTOperator',['../classROCKSDB__NAMESPACE_1_1StringAppendTESTOperator.html',1,'ROCKSDB_NAMESPACE']]],
  ['stringbuilderjni_6780',['StringBuilderJni',['../classROCKSDB__NAMESPACE_1_1StringBuilderJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['stringfs_6781',['StringFS',['../classROCKSDB__NAMESPACE_1_1test_1_1StringFS.html',1,'ROCKSDB_NAMESPACE::test']]],
  ['stringlists_6782',['StringLists',['../classROCKSDB__NAMESPACE_1_1StringLists.html',1,'ROCKSDB_NAMESPACE']]],
  ['stringlogger_6783',['StringLogger',['../classROCKSDB__NAMESPACE_1_1test_1_1StringLogger.html',1,'ROCKSDB_NAMESPACE::test::StringLogger'],['../classROCKSDB__NAMESPACE_1_1StringLogger.html',1,'ROCKSDB_NAMESPACE::StringLogger']]],
  ['stringsink_6784',['StringSink',['../classROCKSDB__NAMESPACE_1_1test_1_1StringFS_1_1StringSink.html',1,'ROCKSDB_NAMESPACE::test::StringFS::StringSink'],['../classROCKSDB__NAMESPACE_1_1test_1_1StringSink.html',1,'ROCKSDB_NAMESPACE::test::StringSink']]],
  ['stringsource_6785',['StringSource',['../classROCKSDB__NAMESPACE_1_1log_1_1LogTest_1_1StringSource.html',1,'ROCKSDB_NAMESPACE::log::LogTest::StringSource'],['../classROCKSDB__NAMESPACE_1_1test_1_1StringSource.html',1,'ROCKSDB_NAMESPACE::test::StringSource']]],
  ['striped_6786',['Striped',['../classROCKSDB__NAMESPACE_1_1Striped.html',1,'ROCKSDB_NAMESPACE']]],
  ['striped_3c_20rocksdb_5fnamespace_3a_3aport_3a_3amutex_2c_20rocksdb_5fnamespace_3a_3aslice_20_3e_6787',['Striped&lt; ROCKSDB_NAMESPACE::port::Mutex, ROCKSDB_NAMESPACE::Slice &gt;',['../classROCKSDB__NAMESPACE_1_1Striped.html',1,'ROCKSDB_NAMESPACE']]],
  ['striperep_6788',['StripeRep',['../classROCKSDB__NAMESPACE_1_1RangeDelAggregator_1_1StripeRep.html',1,'ROCKSDB_NAMESPACE::RangeDelAggregator']]],
  ['subbatchcounter_6789',['SubBatchCounter',['../structROCKSDB__NAMESPACE_1_1SubBatchCounter.html',1,'ROCKSDB_NAMESPACE']]],
  ['subcode_6790',['SubCode',['../enumorg_1_1rocksdb_1_1Status_1_1SubCode.html',1,'org::rocksdb::Status']]],
  ['subcodejni_6791',['SubCodeJni',['../classROCKSDB__NAMESPACE_1_1SubCodeJni.html',1,'ROCKSDB_NAMESPACE']]],
  ['subcompactionstate_6792',['SubcompactionState',['../structROCKSDB__NAMESPACE_1_1CompactionJob_1_1SubcompactionState.html',1,'ROCKSDB_NAMESPACE::CompactionJob']]],
  ['subtree_5ftemplated_6793',['subtree_templated',['../classtoku_1_1omt__internal_1_1subtree__templated.html',1,'toku::omt_internal']]],
  ['subtree_5ftemplated_3c_20supports_5fmarks_20_3e_6794',['subtree_templated&lt; supports_marks &gt;',['../classtoku_1_1omt__internal_1_1subtree__templated.html',1,'toku::omt_internal']]],
  ['subtree_5ftemplated_3c_20true_20_3e_6795',['subtree_templated&lt; true &gt;',['../classtoku_1_1omt__internal_1_1subtree__templated_3_01true_01_4.html',1,'toku::omt_internal']]],
  ['suggestion_6796',['Suggestion',['../classadvisor_1_1rule__parser_1_1Suggestion.html',1,'advisor::rule_parser']]],
  ['superversion_6797',['SuperVersion',['../structROCKSDB__NAMESPACE_1_1SuperVersion.html',1,'ROCKSDB_NAMESPACE']]],
  ['superversioncontext_6798',['SuperVersionContext',['../structROCKSDB__NAMESPACE_1_1SuperVersionContext.html',1,'ROCKSDB_NAMESPACE']]],
  ['syncpoint_6799',['SyncPoint',['../classROCKSDB__NAMESPACE_1_1SyncPoint.html',1,'ROCKSDB_NAMESPACE']]],
  ['syncpointpair_6800',['SyncPointPair',['../structROCKSDB__NAMESPACE_1_1SyncPoint_1_1SyncPointPair.html',1,'ROCKSDB_NAMESPACE::SyncPoint']]],
  ['systemclock_6801',['SystemClock',['../classROCKSDB__NAMESPACE_1_1SystemClock.html',1,'ROCKSDB_NAMESPACE']]],
  ['systemclockwrapper_6802',['SystemClockWrapper',['../classROCKSDB__NAMESPACE_1_1SystemClockWrapper.html',1,'ROCKSDB_NAMESPACE']]]
];
